project:
  type: website

website:
  title: "Learn by Blogging"
  description: "Senthil Kumar's Personal Blog"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/senthilkumarm1901
      - icon: linkedin
        href: https://www.linkedin.com/in/senthilkumarm1901
format:
  html:
    theme: cosmo
    css: styles.css
    



