<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Senthil Kumar">

<title>12. Architecting Hybrid Container-Based Workloads – Foundational Questions. Visual Answers. Mastering AWS Fundamentals.</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-multi-account-strategies.html" rel="next">
<link href="./11-serverless-data-analytics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81dce849c25865aa69203cbf510b76f1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-hybrid-container-workloads.html"><span class="chapter-title">12. Architecting Hybrid Container-Based Workloads</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundational Questions. Visual Answers. Mastering AWS Fundamentals.</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Foundational Questions. Visual Answers. Mastering AWS Fundamentals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Introduction to AWS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-security.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">02. Security</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-compute.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">03. Compute</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-networking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">04. Networking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-storage.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">05. Storage</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-databases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">06. Databases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-monitoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">07. Monitoring</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">08. Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-architecting-serverless-backend-solution-in-aws.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Architecting a Serverless Web Backend</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-serverless-data-analytics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Architecting Serverless Data Analytics Solutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-hybrid-container-workloads.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">12. Architecting Hybrid Container-Based Workloads</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-multi-account-strategies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Architecting for Account Governance and Multi-Account Management</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-references-disclosure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Disclosure</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-to-architect-a-hybrid-container-based-solution-on-aws" id="toc-how-to-architect-a-hybrid-container-based-solution-on-aws" class="nav-link active" data-scroll-target="#how-to-architect-a-hybrid-container-based-solution-on-aws">How to Architect a Hybrid, Container-Based Solution on AWS</a></li>
  <li><a href="#the-method-nine-steps-across-two-environments" id="toc-the-method-nine-steps-across-two-environments" class="nav-link" data-scroll-target="#the-method-nine-steps-across-two-environments">12.1 The Method: nine steps across two environments</a></li>
  <li><a href="#sec-drivers" id="toc-sec-drivers" class="nav-link" data-scroll-target="#sec-drivers">12.2 Step 1 — Turn requirements into drivers</a></li>
  <li><a href="#sec-connect" id="toc-sec-connect" class="nav-link" data-scroll-target="#sec-connect">12.3 Step 2 — Connect the two environments</a>
  <ul class="collapse">
  <li><a href="#the-connectivity-decision" id="toc-the-connectivity-decision" class="nav-link" data-scroll-target="#the-connectivity-decision">12.3.1 The connectivity decision</a></li>
  <li><a href="#direct-connect-topology" id="toc-direct-connect-topology" class="nav-link" data-scroll-target="#direct-connect-topology">12.3.2 Direct Connect topology</a></li>
  <li><a href="#the-alternatives-and-when-theyd-win" id="toc-the-alternatives-and-when-theyd-win" class="nav-link" data-scroll-target="#the-alternatives-and-when-theyd-win">12.3.3 The alternatives — and when they’d win</a></li>
  <li><a href="#scaling-connectivity-aws-transit-gateway" id="toc-scaling-connectivity-aws-transit-gateway" class="nav-link" data-scroll-target="#scaling-connectivity-aws-transit-gateway">12.3.4 Scaling connectivity: AWS Transit Gateway</a></li>
  </ul></li>
  <li><a href="#sec-compute" id="toc-sec-compute" class="nav-link" data-scroll-target="#sec-compute">12.4 Step 3 — Run the containers, privately</a>
  <ul class="collapse">
  <li><a href="#launch-type-decision-why-ec2-not-fargate" id="toc-launch-type-decision-why-ec2-not-fargate" class="nav-link" data-scroll-target="#launch-type-decision-why-ec2-not-fargate">12.4.1 Launch-type decision: why EC2, not Fargate</a></li>
  <li><a href="#private-subnets-outbound-egress-and-the-nat-trap" id="toc-private-subnets-outbound-egress-and-the-nat-trap" class="nav-link" data-scroll-target="#private-subnets-outbound-egress-and-the-nat-trap">12.4.2 Private subnets, outbound egress, and the NAT trap</a></li>
  </ul></li>
  <li><a href="#sec-db" id="toc-sec-db" class="nav-link" data-scroll-target="#sec-db">12.5 Step 4 — Migrate the database, resiliently</a>
  <ul class="collapse">
  <li><a href="#high-availability-multi-az-db-instance-one-standby" id="toc-high-availability-multi-az-db-instance-one-standby" class="nav-link" data-scroll-target="#high-availability-multi-az-db-instance-one-standby">12.5.1 High availability: Multi-AZ DB <em>instance</em> (one standby)</a></li>
  <li><a href="#even-higher-availability-multi-az-db-cluster-two-readable-standbys" id="toc-even-higher-availability-multi-az-db-cluster-two-readable-standbys" class="nav-link" data-scroll-target="#even-higher-availability-multi-az-db-cluster-two-readable-standbys">12.5.2 Even higher availability: Multi-AZ DB <em>cluster</em> (two readable standbys)</a></li>
  <li><a href="#scaling-reads-read-replicas" id="toc-scaling-reads-read-replicas" class="nav-link" data-scroll-target="#scaling-reads-read-replicas">12.5.3 Scaling reads: read replicas</a></li>
  <li><a href="#choosing-a-scaling-axis" id="toc-choosing-a-scaling-axis" class="nav-link" data-scroll-target="#choosing-a-scaling-axis">12.5.4 Choosing a scaling axis</a></li>
  <li><a href="#the-migration-itself-aws-dms" id="toc-the-migration-itself-aws-dms" class="nav-link" data-scroll-target="#the-migration-itself-aws-dms">12.5.5 The migration itself: AWS DMS</a></li>
  </ul></li>
  <li><a href="#sec-storage" id="toc-sec-storage" class="nav-link" data-scroll-target="#sec-storage">12.6 Step 5 — Share storage across the boundary</a></li>
  <li><a href="#sec-operate" id="toc-sec-operate" class="nav-link" data-scroll-target="#sec-operate">12.7 Step 6 — Operate one way across both environments</a></li>
  <li><a href="#sec-observability" id="toc-sec-observability" class="nav-link" data-scroll-target="#sec-observability">12.8 Step 7 — Observe both sides through one pane</a></li>
  <li><a href="#sec-scale" id="toc-sec-scale" class="nav-link" data-scroll-target="#sec-scale">12.9 Step 8 — Scale the moving parts</a></li>
  <li><a href="#sec-dr" id="toc-sec-dr" class="nav-link" data-scroll-target="#sec-dr">12.10 Step 9 — Design for disaster recovery</a></li>
  <li><a href="#sec-reference" id="toc-sec-reference" class="nav-link" data-scroll-target="#sec-reference">12.11 The reference architecture, end to end</a></li>
  <li><a href="#sec-not" id="toc-sec-not" class="nav-link" data-scroll-target="#sec-not">12.12 When <em>not</em> to use these choices</a></li>
  <li><a href="#sec-cheatsheet" id="toc-sec-cheatsheet" class="nav-link" data-scroll-target="#sec-cheatsheet">12.13 Architect’s cheat sheet</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources">Sources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">12. Architecting Hybrid Container-Based Workloads</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Senthil Kumar </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>👈 <strong>Back to:</strong> <a href="https://senthilkumarm1901.github.io/learn_by_blogging/blog.html">📝 Blog</a> | <a href="https://www.linkedin.com/in/senthilkumarm1901">💼 LinkedIn</a> | <a href="https://medium.com/@senthilkumar.m1901">✍️ Medium</a></p>
<hr>
<section id="how-to-architect-a-hybrid-container-based-solution-on-aws" class="level2">
<h2 class="anchored" data-anchor-id="how-to-architect-a-hybrid-container-based-solution-on-aws">How to Architect a Hybrid, Container-Based Solution on AWS</h2>
<blockquote class="blockquote">
<ul>
<li>❓ When <em>half</em> your workloads stay on-premises and half move to AWS, how do you connect the two, keep containers portable, migrate a database with near-zero downtime, and stay resilient — without rewriting applications?</li>
<li>Hint: same discipline as <a href="./10-architecting-serverless-backend-solution-in-aws.html">10. Serverless Backend</a> and <a href="./11-serverless-data-analytics.html">11. Serverless Data Analytics</a> — <strong>requirements → architectural drivers → candidate services → trade-offs → decision → justified rejections</strong>. What changes is that the answer now spans <em>two</em> environments joined by a network.</li>
</ul>
</blockquote>
<p><strong>Running example used throughout this chapter</strong></p>
<blockquote class="blockquote">
<p>An enterprise runs <strong>containerised applications and PostgreSQL databases</strong> in its own data centres. <strong>Data-centre contracts are expiring in waves</strong>, so it will move <strong>half the workloads to AWS now</strong> and keep the rest on-premises until their contracts end — a genuinely <strong>hybrid</strong> end state, not a big-bang migration.</p>
<p><strong>The customer’s constraints:</strong></p>
<ul>
<li><strong>Dedicated, consistent, low-latency connectivity</strong> between the data centre and AWS for high-volume traffic.</li>
<li><strong>Keep containers private</strong> (no inbound internet) but allow <strong>outbound</strong> (e.g.&nbsp;to pull updates).</li>
<li><strong>Same orchestration tooling</strong> on both sides to simplify operations.</li>
<li><strong>Lift-and-shift PostgreSQL</strong> to AWS with <strong>no application code rewrite</strong>.</li>
<li><strong>High uptime, resilience, fault tolerance</strong> — no single points of failure.</li>
<li>On-prem apps must <strong>store/read data in AWS over NFS</strong> without refactoring.</li>
</ul>
</blockquote>
<hr>
</section>
<section id="the-method-nine-steps-across-two-environments" class="level2">
<h2 class="anchored" data-anchor-id="the-method-nine-steps-across-two-environments">12.1 The Method: nine steps across two environments</h2>
<p>A hybrid design decomposes into the same reasoning chain as a cloud-only one — but every answer must hold in <strong>both</strong> environments, and the network underneath them.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    N["1. Connect&lt;br&gt;DC to AWS"] --&gt; C["2. Run containers&lt;br&gt;privately"]
    C --&gt; D["3. Migrate the&lt;br&gt;database"]
    D --&gt; S["4. Share storage&lt;br&gt;across the boundary"]
    S --&gt; O["5. Operate, observe,&lt;br&gt;scale, protect"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Question the architect answers</th>
<th>Winning choice (this case)</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>What are the real architectural drivers?</td>
<td>—</td>
<td><a href="#sec-drivers">12.2</a></td>
</tr>
<tr class="even">
<td>2</td>
<td>How do the two environments connect?</td>
<td><strong>AWS Direct Connect</strong> (+ VPN failover)</td>
<td><a href="#sec-connect">12.3</a></td>
</tr>
<tr class="odd">
<td>3</td>
<td>What runs the containers, privately?</td>
<td><strong>ECS on EC2 launch type</strong> + NAT per AZ</td>
<td><a href="#sec-compute">12.4</a></td>
</tr>
<tr class="even">
<td>4</td>
<td>How does PostgreSQL move, resiliently?</td>
<td><strong>RDS Multi-AZ</strong> + <strong>DMS</strong>, read replicas</td>
<td><a href="#sec-db">12.5</a></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Where does shared data live?</td>
<td><strong>S3 File Gateway</strong> + <strong>S3</strong></td>
<td><a href="#sec-storage">12.6</a></td>
</tr>
<tr class="even">
<td>6</td>
<td>How is it operated the same way on both sides?</td>
<td><strong>ECS Anywhere, Systems Manager, AWS Backup</strong></td>
<td><a href="#sec-operate">12.7</a></td>
</tr>
<tr class="odd">
<td>7</td>
<td>How do we know it is healthy?</td>
<td>CloudWatch across DC <strong>and</strong> AWS</td>
<td><a href="#sec-observability">12.8</a></td>
</tr>
<tr class="even">
<td>8</td>
<td>What scales, and how?</td>
<td>Cluster + service auto scaling</td>
<td><a href="#sec-scale">12.9</a></td>
</tr>
<tr class="odd">
<td>9</td>
<td>How much disaster recovery do we buy?</td>
<td>Cheapest tier that meets RTO/RPO</td>
<td><a href="#sec-dr">12.10</a></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> In hybrid design, the <strong>network is the foundation</strong> — get connectivity wrong and every other decision inherits its latency, cost and failure modes.</p>
</blockquote>
<hr>
</section>
<section id="sec-drivers" class="level2">
<h2 class="anchored" data-anchor-id="sec-drivers">12.2 Step 1 — Turn requirements into drivers</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How does “half here, half there, for years” change the design?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    R1["Half on-prem, half AWS,&lt;br&gt;for a long time"] --&gt; D1["True hybrid, not big-bang"]
    R2["High-volume, consistent traffic"] --&gt; D2["Dedicated connectivity"]
    R3["Private containers,&lt;br&gt;outbound only"] --&gt; D3["Private subnets + NAT"]
    R4["Same tooling both sides"] --&gt; D4["Consistent orchestration"]
    R5["Lift-and-shift PostgreSQL,&lt;br&gt;no rewrite"] --&gt; D5["Managed compatible DB"]
    R6["High uptime, no SPOF"] --&gt; D6["Multi-AZ + redundant links"]
    R7["NFS access to AWS data"] --&gt; D7["Hybrid file storage"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Customer requirement</th>
<th>Architectural driver</th>
<th>Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Half on-prem for years</td>
<td><strong>Hybrid, not migration</strong></td>
<td>Invest in durable connectivity and shared tooling</td>
</tr>
<tr class="even">
<td>High-volume, consistent traffic</td>
<td><strong>Dedicated connectivity</strong></td>
<td>Direct Connect, not internet VPN as the primary</td>
</tr>
<tr class="odd">
<td>Private containers, outbound only</td>
<td><strong>Controlled egress</strong></td>
<td>Private subnets + NAT / VPC endpoints</td>
</tr>
<tr class="even">
<td>Same tooling both sides</td>
<td><strong>Operational consistency</strong></td>
<td>ECS Anywhere + Systems Manager agents on-prem</td>
</tr>
<tr class="odd">
<td>No application rewrite</td>
<td><strong>Compatibility over optimality</strong></td>
<td>Managed engine that speaks the same wire protocol</td>
</tr>
<tr class="even">
<td>No single points of failure</td>
<td><strong>Redundancy at every layer</strong></td>
<td>Multi-AZ, multi-link, multi-NAT</td>
</tr>
<tr class="odd">
<td>Keep NFS</td>
<td><strong>Protocol preservation</strong></td>
<td>Hybrid file gateway, not a client refactor</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>⚠️ Plan the address space before anything else.</strong> The most common hybrid blocker is <strong>overlapping CIDR ranges</strong> between the data centre and the VPC — routing simply cannot resolve it, and the fix (re-IP or NAT the overlap) is painful once workloads are live. Agree non-overlapping ranges at design time.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> “Half and half, for a long time” is the driver that shapes everything: it rules out a big-bang migration and forces you to invest in <strong>durable connectivity and consistent tooling</strong> rather than treating on-prem as throwaway.</p>
</blockquote>
<hr>
</section>
<section id="sec-connect" class="level2">
<h2 class="anchored" data-anchor-id="sec-connect">12.3 Step 2 — Connect the two environments</h2>
<blockquote class="blockquote">
<ul>
<li>❓ Dedicated line, encrypted tunnel, or a central hub — and when does each win?</li>
</ul>
</blockquote>
<section id="the-connectivity-decision" class="level3">
<h3 class="anchored" data-anchor-id="the-connectivity-decision">12.3.1 The connectivity decision</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    Q0["Connect DC to AWS"] --&gt; Q1{"Need consistent,&lt;br&gt;dedicated, high throughput?"}
    Q1 --&gt;|Yes| DX["AWS Direct Connect - CHOSEN&lt;br&gt;private, off the public internet"]
    Q1 --&gt;|"No / quick + cheap"| VPN["Site-to-Site VPN&lt;br&gt;IPsec over internet"]
    DX --&gt; Q2{"Many VPCs / accounts /&lt;br&gt;Regions to interconnect?"}
    Q2 --&gt;|Yes| TGW["Add Transit Gateway&lt;br&gt;+ Direct Connect Gateway"]
    Q2 --&gt;|No| DONE["Direct Connect + VPN failover"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: AWS Direct Connect.</strong> The customer needs <strong>consistent, dedicated throughput</strong> for high-volume DC↔︎AWS traffic. Direct Connect keeps traffic <strong>on the AWS global network, never on the public internet</strong>, which removes the latency spikes and bottlenecks you’d get over the internet.</p>
<blockquote class="blockquote">
<p><strong>🔴 Private is not the same as encrypted.</strong> Direct Connect traffic is <strong>not encrypted by default</strong> — it is a private circuit, not a secure one. If your compliance posture requires encryption in transit across the link, you must add it: <strong>MACsec</strong> (on supported dedicated connections) for layer-2 encryption, or run an <strong>IPsec Site-to-Site VPN over the Direct Connect public virtual interface</strong>. Do not let “off the public internet” be read as “encrypted”.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>⏱️ Direct Connect has a lead time — and here it is on the critical path.</strong> A <strong>dedicated</strong> connection requires a cross-connect at a Direct Connect location (LOA-CFA, partner coordination, physical patching) and typically takes <strong>weeks to months</strong>. Since this customer’s timeline is driven by <strong>expiring data-centre contracts</strong>, order the circuit early, and consider a <strong>hosted connection</strong> from an AWS Partner — provisioned in far less time and available in sub-1 Gbps increments — to bridge the gap.</p>
</blockquote>
</section>
<section id="direct-connect-topology" class="level3">
<h3 class="anchored" data-anchor-id="direct-connect-topology">12.3.2 Direct Connect topology</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    DC["Data Center"] &lt;--&gt; DX1["Direct Connect&lt;br&gt;Location A"]
    BO["Branch Office"] &lt;--&gt; DX2["Direct Connect&lt;br&gt;Location B"]
    DX1 &lt;--&gt;|"SiteLink between&lt;br&gt;DX locations"| DX2
    DX1 --&gt; R["Any AWS Region"]
    DX2 --&gt; R
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>SiteLink</strong> lets you send data <strong>between Direct Connect locations</strong>, creating private links across your global offices/data centres.</li>
<li>A <strong>Direct Connect Gateway</strong> is what lets one connection reach <strong>multiple VPCs across accounts and Regions</strong> — without it, a private virtual interface maps to a single VPC.</li>
<li>Each dedicated connection is <strong>a single link</strong> — so AWS <strong>recommends a second connection for redundancy</strong>. Without a backup (second DX <strong>or</strong> an IPsec VPN), <strong>VPC traffic is dropped on failure</strong>.</li>
</ul>
</section>
<section id="the-alternatives-and-when-theyd-win" class="level3">
<h3 class="anchored" data-anchor-id="the-alternatives-and-when-theyd-win">12.3.3 The alternatives — and when they’d win</h3>
<p><strong>Site-to-Site VPN</strong> <em>(virtual private gateway + customer gateway, with redundancy)</em></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph AWS["Amazon VPC"]
        VGW["Virtual Private Gateway&lt;br&gt;AWS-side concentrator"]
        E1["EC2 in AZ 1"]
        E2["EC2 in AZ 2"]
        VGW --- E1
        VGW --- E2
    end
    subgraph DCn["Customer Network"]
        CGW1["Customer Gateway 1"]
        CGW2["Customer Gateway 2"]
        SRV["Servers"]
        CGW1 --- SRV
        CGW2 --- SRV
    end
    VGW &lt;--&gt;|"IPsec VPN"| CGW1
    VGW &lt;--&gt;|"IPsec VPN redundant"| CGW2
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>How it works</th>
<th>Prefer when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Direct Connect</strong> (chosen)</td>
<td>Private, dedicated fibre to AWS; off the public internet</td>
<td>You need <strong>consistent</strong> throughput/latency for high volume</td>
</tr>
<tr class="even">
<td><strong>Site-to-Site VPN</strong></td>
<td>IPsec tunnel over the internet via a virtual private gateway</td>
<td>You want it <strong>fast and cheap</strong>, or as <strong>failover</strong> for Direct Connect</td>
</tr>
<tr class="odd">
<td><strong>Client VPN</strong></td>
<td>Managed remote-access VPN (OpenVPN-based) for individual users</td>
<td><strong>Remote workforce</strong> needs to reach VPC/on-prem resources</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>⚠️ VPN failover is survival, not capacity.</strong> Each Site-to-Site VPN tunnel is capped at roughly <strong>1.25 Gbps</strong>. Failing a 10 Gbps Direct Connect over to a VPN is a <strong>capacity cliff</strong>, not a transparent switch — expect degraded service. For genuinely high-bandwidth production, AWS’s resiliency models recommend <strong>two Direct Connect connections at two separate locations</strong> (with the VPN as a third line of defence). Also note that when both paths are up, <strong>BGP path selection prefers Direct Connect</strong>, so failover behaviour depends on correct BGP configuration, not luck.</p>
</blockquote>
<p><strong>Client VPN</strong> covers three access shapes worth remembering:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    CE["Client VPN endpoint"] --&gt; S1["Scenario 1&lt;br&gt;access a single VPC"]
    CE --&gt; S2["Scenario 2&lt;br&gt;access on-prem only"]
    CE --&gt; S3["Scenario 3&lt;br&gt;access VPC + client-to-client"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="scaling-connectivity-aws-transit-gateway" class="level3">
<h3 class="anchored" data-anchor-id="scaling-connectivity-aws-transit-gateway">12.3.4 Scaling connectivity: AWS Transit Gateway</h3>
<p>Direct Connect answers <em>one</em> DC to <em>one</em> VPC. Once you have <strong>many VPCs, accounts or Regions</strong>, point-to-point peering explodes into an unmanageable mesh. <strong>Transit Gateway</strong> is the hub-and-spoke fix.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    subgraph Without["Without Transit Gateway - mesh"]
        A1["VPC A"] --- A2["VPC B"]
        A2 --- A3["VPC C"]
        A1 --- A3
        A1 --- CG1["Customer GW"]
        A2 --- CG1
        A3 --- CG1
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    subgraph With["With Transit Gateway - hub"]
        TGW(("AWS Transit&lt;br&gt;Gateway"))
        V1["VPC A"] --- TGW
        V2["VPC B"] --- TGW
        V3["VPC C"] --- TGW
        CG["Customer GW / VPN"] --- TGW
        DXG["Direct Connect Gateway"] --- TGW
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>Each connection is made <strong>once</strong> to the hub; route tables control who talks to whom.</li>
<li><strong>Inter-Region peering</strong> links transit gateways over the AWS backbone; that traffic <strong>is</strong> automatically encrypted and never traverses the public internet — unlike the Direct Connect link itself.</li>
<li>Pairs naturally with a <strong>Direct Connect Gateway</strong> for <strong>multi-Region + multi-VPC</strong> estates.</li>
</ul>
<p>For VPC, subnet and routing fundamentals, see <a href="./04-networking.html">04. Networking</a>.</p>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Choose <strong>Direct Connect</strong> for consistent, high-volume hybrid traffic — but order it early, encrypt it explicitly, and size the fallback honestly. Keep a <strong>VPN as automatic failover</strong> so a single link is never a SPOF, and reach for <strong>Transit Gateway + Direct Connect Gateway</strong> the moment the topology grows past a couple of VPCs.</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-compute" class="level2">
<h2 class="anchored" data-anchor-id="sec-compute">12.4 Step 3 — Run the containers, privately</h2>
<blockquote class="blockquote">
<ul>
<li>❓ ECS or EKS? EC2 or Fargate? And how do private containers still reach the internet <em>outbound</em>?</li>
</ul>
</blockquote>
<section id="launch-type-decision-why-ec2-not-fargate" class="level3">
<h3 class="anchored" data-anchor-id="launch-type-decision-why-ec2-not-fargate">12.4.1 Launch-type decision: why EC2, not Fargate</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    W["Container hosting on AWS"] --&gt; Q1{"Need a custom AMI?"}
    Q1 --&gt;|No| Q2{"Need SSH to the&lt;br&gt;underlying hosts?"}
    Q1 --&gt;|Yes| EC2["EC2 launch type - CHOSEN"]
    Q2 --&gt;|Yes| EC2
    Q2 --&gt;|No| FAR["AWS Fargate&lt;br&gt;serverless, no host access"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: Amazon ECS with the EC2 launch type.</strong> The customer requires a <strong>custom AMI</strong> and <strong>SSH access</strong> to the underlying instances (to keep management operations similar across on-prem and cloud). <strong>Fargate supports neither</strong>, so EC2 is the correct launch type here — a rare case where the <em>serverless</em> option is rejected on purpose.</p>
<p><strong>ECS on EC2 architecture</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    IMG["Container image"] --&gt; REG["Container registry&lt;br&gt;ECR or Docker Hub"]
    TD["Task definition"] --&gt; CL
    SVC["Service&lt;br&gt;task def + service description"] --&gt; CL
    subgraph CL["ECS cluster in VPC"]
        subgraph AZ1["AZ 1"]
            I1["EC2 instance&lt;br&gt;ECS agent + tasks"]
        end
        subgraph AZ2["AZ 2"]
            I2["EC2 instance&lt;br&gt;ECS agent + tasks"]
        end
    end
    REG --&gt; I1
    REG --&gt; I2
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>The <strong>ECS agent</strong> runs on <strong>each EC2 instance</strong> and lets ECS orchestrate the nodes you own and manage.</li>
<li>Contrast with <strong>Fargate</strong>, where each task gets its <strong>own elastic network interface</strong> and there are <strong>no EC2 instances to manage</strong> — great when you <em>don’t</em> need a custom AMI or host access.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>EC2 launch type (chosen)</th>
<th>Fargate launch type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>You manage</td>
<td>The EC2 cluster (AMI, patching, SSH)</td>
<td>Nothing below the task</td>
</tr>
<tr class="even">
<td>Custom AMI</td>
<td>✅ Yes</td>
<td>❌ No</td>
</tr>
<tr class="odd">
<td>SSH to host</td>
<td>✅ Yes</td>
<td>❌ No</td>
</tr>
<tr class="even">
<td>Best when</td>
<td>Custom AMI, host control, consistent tooling</td>
<td>“Just run my container”, no infra ops</td>
</tr>
</tbody>
</table>
<p>See <a href="./03-compute.html">03. Compute</a> for the wider EC2 and container landscape.</p>
</section>
<section id="private-subnets-outbound-egress-and-the-nat-trap" class="level3">
<h3 class="anchored" data-anchor-id="private-subnets-outbound-egress-and-the-nat-trap">12.4.2 Private subnets, outbound egress, and the NAT trap</h3>
<p>The containers must be <strong>private (no inbound internet)</strong> but need <strong>outbound</strong> (updates). A <strong>NAT gateway</strong> provides exactly that.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph AZ1["AZ 1"]
        E1["ECS tasks&lt;br&gt;private subnet"] --&gt; N1["NAT gateway 1&lt;br&gt;public subnet"]
    end
    subgraph AZ2["AZ 2"]
        E2["ECS tasks&lt;br&gt;private subnet"] --&gt; N2["NAT gateway 2&lt;br&gt;public subnet"]
    end
    N1 --&gt; IGW["Internet gateway"]
    N2 --&gt; IGW
    IGW --&gt; NET["Internet&lt;br&gt;downloads and updates"]
    NET -.-&gt;|"no unsolicited inbound"| E1
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>A NAT device <strong>replaces the private instance’s source IP</strong> with its own and translates responses back — so instances <strong>initiate</strong> outbound connections but <strong>can’t receive</strong> unsolicited inbound ones.</li>
<li><strong>NAT gateway (managed)</strong> is recommended over a self-run <strong>NAT instance</strong> for <strong>better availability, bandwidth and less admin</strong>.</li>
<li><strong>Public NAT gateway</strong> (Elastic IP, routes to internet gateway) vs <strong>private NAT gateway</strong> (routes to other VPCs/on-prem via TGW or VGW, no Elastic IP).</li>
</ul>
<blockquote class="blockquote">
<p><strong>🔴 One NAT gateway is a single point of failure.</strong> A NAT gateway is <strong>scoped to a single Availability Zone</strong>. If you put one NAT gateway in one public subnet and route every private subnet to it, an AZ failure takes <strong>all</strong> your containers’ egress down — which directly contradicts the customer’s “no single points of failure” requirement. Deploy <strong>one NAT gateway per AZ</strong> and give each AZ’s private subnet its own route table pointing at its local NAT gateway. This also avoids paying for cross-AZ data transfer on every outbound byte.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>💰 Don’t pay NAT charges for traffic that never needed the internet.</strong> NAT gateways bill per hour <strong>and per GB processed</strong>. ECS pulling images from <strong>ECR</strong>, the <strong>SSM Agent</strong>, CloudWatch Logs and S3 access all go through NAT by default. Replace that with <strong>VPC endpoints</strong>: a <strong>gateway endpoint</strong> for S3 (no hourly charge) and <strong>interface endpoints</strong> for ECR API/DKR, SSM, and CloudWatch Logs. You cut cost <em>and</em> keep the traffic off the internet path entirely — a better fit for “private containers” than NAT alone.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> “Serverless by default” is not a law. When the driver is a <strong>custom AMI + host SSH + consistent tooling</strong>, <strong>ECS on EC2</strong> is the right call. Pair private subnets with <strong>one managed NAT gateway per AZ</strong> for resilient outbound-only access, and use <strong>VPC endpoints</strong> for AWS-service traffic.</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-db" class="level2">
<h2 class="anchored" data-anchor-id="sec-db">12.5 Step 4 — Migrate the database, resiliently</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How do you lift-and-shift PostgreSQL with near-zero downtime and no single point of failure?</li>
</ul>
</blockquote>
<p><strong>Chosen: Amazon RDS for PostgreSQL, Multi-AZ, migrated with AWS DMS.</strong> A managed engine keeps the app code unchanged (lift-and-shift), Multi-AZ delivers the high availability the customer demands, and DMS moves the data while the source stays live.</p>
<p>For RDS fundamentals, backups and where databases sit in your VPC, see <a href="./06-databases.html">06. Databases</a>.</p>
<section id="high-availability-multi-az-db-instance-one-standby" class="level3">
<h3 class="anchored" data-anchor-id="high-availability-multi-az-db-instance-one-standby">12.5.1 High availability: Multi-AZ DB <em>instance</em> (one standby)</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    APP["Application"] --&gt; PRI["Primary DB&lt;br&gt;AZ 1"]
    PRI --&gt;|"synchronous&lt;br&gt;replication"| STB["Standby DB&lt;br&gt;AZ 2"]
    PRI -.-&gt;|"auto-failover on failure&lt;br&gt;same endpoint"| STB
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>RDS keeps a <strong>synchronous</strong> standby in <strong>another AZ</strong> and <strong>fails over automatically</strong> — the <strong>database endpoint doesn’t change</strong>, so applications reconnect transparently.</li>
<li>The standby is <strong>not readable</strong>; it exists purely for availability.</li>
<li>A <strong>single</strong> RDS instance does <strong>not</strong> self-heal; HA <strong>requires</strong> Multi-AZ.</li>
</ul>
</section>
<section id="even-higher-availability-multi-az-db-cluster-two-readable-standbys" class="level3">
<h3 class="anchored" data-anchor-id="even-higher-availability-multi-az-db-cluster-two-readable-standbys">12.5.2 Even higher availability: Multi-AZ DB <em>cluster</em> (two readable standbys)</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    W["Writer endpoint"] --&gt; P["Primary writer&lt;br&gt;AZ 1"]
    P --&gt;|"replicate"| S1["Readable standby&lt;br&gt;AZ 2"]
    P --&gt;|"replicate"| S2["Readable standby&lt;br&gt;AZ 3"]
    R["Reader endpoint"] --&gt; S1
    R --&gt; S2
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>This is a <strong>different deployment type</strong> from the Multi-AZ DB <em>instance</em> above — in the console and docs it is the <strong>Multi-AZ DB cluster</strong>, available for <strong>PostgreSQL and MySQL</strong>.</li>
<li>Three AZs, <strong>two readable standbys</strong>: <strong>failover typically under ~35 seconds</strong>, up to <strong>~2× faster commit latency</strong>, plus <strong>extra read capacity</strong>.</li>
</ul>
</section>
<section id="scaling-reads-read-replicas" class="level3">
<h3 class="anchored" data-anchor-id="scaling-reads-read-replicas">12.5.3 Scaling reads: read replicas</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    APPW["App servers&lt;br&gt;read and write"] --&gt;|"read + write"| PRI["Primary DB"]
    PRI --&gt;|"asynchronous&lt;br&gt;replication"| RR["Read replica&lt;br&gt;read-only"]
    BI["BI / reporting&lt;br&gt;app server"] --&gt;|"read-only queries"| RR
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>Read replicas</strong> offload <strong>read-heavy / CPU-intensive</strong> work (e.g.&nbsp;BI reports) off the primary via <strong>asynchronous</strong> replication, raising aggregate read throughput.</li>
<li>Replicas can be <strong>promoted</strong> to standalone instances if needed.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Don’t confuse the three:</strong> <strong>Multi-AZ standby = availability</strong> (synchronous, auto-failover, not readable). <strong>Multi-AZ DB cluster = availability + some read capacity</strong>. <strong>Read replica = performance/scale</strong> (asynchronous, read-only, replica lag). They solve different problems and are often used together.</p>
</blockquote>
</section>
<section id="choosing-a-scaling-axis" class="level3">
<h3 class="anchored" data-anchor-id="choosing-a-scaling-axis">12.5.4 Choosing a scaling axis</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    NEED{"What is the bottleneck?"} --&gt;|"More CPU + storage"| VUP["Scale up vertically&lt;br&gt;bigger instance"]
    NEED --&gt;|"More read CPU only"| RR2["Add read replicas"]
    NEED --&gt;|"More storage only"| AS["RDS Storage Auto Scaling"]
    NEED --&gt;|"More IOPS/throughput"| ST["Switch storage type&lt;br&gt;Provisioned IOPS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>Storage types:</strong> <em>General Purpose SSD</em> (broad, bursty), <em>Provisioned IOPS</em> (I/O-intensive DBs, consistent low latency), <em>Magnetic</em> (legacy — avoid for new work).</li>
<li><strong>RDS Storage Auto Scaling</strong> grows storage automatically toward a max limit with virtually zero downtime.</li>
</ul>
</section>
<section id="the-migration-itself-aws-dms" class="level3">
<h3 class="anchored" data-anchor-id="the-migration-itself-aws-dms">12.5.5 The migration itself: AWS DMS</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    SRC["Source DB&lt;br&gt;on-prem PostgreSQL"] --&gt; SE["Source endpoint"]
    SE --&gt; RT["Replication task&lt;br&gt;DMS replication instance"]
    RT --&gt; TE["Target endpoint"]
    TE --&gt; TGT["Amazon RDS&lt;br&gt;for PostgreSQL"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>DMS is a <strong>replication server</strong> in the cloud: define <strong>source + target endpoints</strong>, run a <strong>task</strong>, and it copies data while the <strong>source stays fully operational</strong> — <strong>near-zero downtime</strong> (there is still a short cutover window).</li>
<li>This is a <strong>homogeneous</strong> migration (PostgreSQL → RDS PostgreSQL), so no <strong>AWS SCT</strong> schema conversion is needed. <em>Heterogeneous</em> migrations (e.g.&nbsp;Oracle → PostgreSQL) do need SCT.</li>
</ul>
<blockquote class="blockquote">
<p><strong>⚠️ DMS migrates data, not your whole schema.</strong> By default DMS creates only the objects needed to move rows — <strong>tables with primary keys</strong>. It does <strong>not</strong> bring across secondary indexes, sequences, default values, foreign keys, constraints, views, triggers or stored procedures. For a homogeneous PostgreSQL move the standard pattern is <strong><code>pg_dump</code>/<code>pg_restore</code> for the schema, then DMS for the bulk data and ongoing change capture</strong>. Also, <strong>CDC from PostgreSQL requires logical replication</strong> on the source (<code>wal_level = logical</code>, or <code>rds.logical_replication</code> on an RDS source) — configure it <em>before</em> you cut over, since it needs a restart.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> For a no-rewrite lift-and-shift, <strong>RDS + DMS</strong> is the default: managed engine keeps the app unchanged, <strong>Multi-AZ</strong> gives HA (endpoint-stable failover), <strong>read replicas</strong> absorb reporting load, and DMS moves data with the source still live — provided you move the schema separately and enable logical replication up front.</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-storage" class="level2">
<h2 class="anchored" data-anchor-id="sec-storage">12.6 Step 5 — Share storage across the boundary</h2>
<blockquote class="blockquote">
<ul>
<li>❓ On-prem apps must keep writing over <strong>NFS</strong>, yet the data has to live in AWS with low local latency. Which storage service?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    Q["On-prem apps write files over NFS,&lt;br&gt;data must live in AWS"] --&gt; Q1{"Keep NFS + low-latency&lt;br&gt;local writes?"}
    Q1 --&gt;|"Pure cloud NFS"| EFS["Amazon EFS&lt;br&gt;NFS + lifecycle, but adds&lt;br&gt;network latency to AWS"]
    Q1 --&gt;|"Hybrid local cache"| SGW["S3 File Gateway - CHOSEN&lt;br&gt;local NFS cache, async to S3"]
    SGW --&gt; S3["Amazon S3&lt;br&gt;lifecycle, CRR, versioning"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: AWS Storage Gateway (S3 File Gateway) + Amazon S3.</strong> The customer must <strong>keep the NFS protocol</strong> for unmodified on-prem apps <strong>and</strong> store the files in AWS. File Gateway gives <strong>local NFS/SMB access with a local cache</strong> (low-latency writes) and <strong>asynchronously</strong> transfers data to <strong>S3</strong>.</p>
<p><strong>S3 File Gateway architecture</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    APP["On-prem apps&lt;br&gt;NFS or SMB"] --&gt; GW["S3 File Gateway&lt;br&gt;VM appliance + local cache"]
    GW --&gt;|"async, encrypted in transit"| S3["Amazon S3"]
    S3 --&gt; LC["Lifecycle to Glacier /&lt;br&gt;Intelligent-Tiering"]
    S3 --&gt; CRR["Cross-Region Replication"]
    CLOUD["AWS apps / analytics"] --&gt; S3
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Why it fits every requirement at once:</p>
<ul>
<li><strong>No refactoring:</strong> apps keep talking <strong>NFS v3/v4.1</strong> (or SMB).</li>
<li><strong>Low latency:</strong> transparent <strong>local caching</strong> buffers apps from network congestion.</li>
<li><strong>Cost management:</strong> data lands in S3, so <strong>lifecycle policies</strong> move cold files to cheaper tiers.</li>
<li><strong>Future-proof:</strong> once fully migrated, apps can read <strong>natively from S3</strong> with no extra data move.</li>
</ul>
<blockquote class="blockquote">
<p><strong>⚠️ Two operational caveats.</strong> (1) Upload is <strong>asynchronous</strong>, so there is a <strong>non-zero RPO</strong> — a file written locally is not instantly durable in S3; size the local cache disk for your write burst and monitor upload lag. (2) If anything writes to the bucket <strong>outside</strong> the gateway, the gateway won’t see it until you run <strong><code>RefreshCache</code></strong> — so treat a File Gateway bucket as gateway-owned, or automate the refresh.</p>
</blockquote>
<p><strong>The wider storage menu (know when each wins):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Service</th>
<th>Type</th>
<th>Prefer when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>S3</strong></td>
<td>Object</td>
<td>Data lakes, unlimited scale, lifecycle/tiering</td>
</tr>
<tr class="even">
<td><strong>S3 File Gateway</strong></td>
<td>Hybrid file → S3</td>
<td>On-prem <strong>NFS/SMB</strong> with cloud-backed storage</td>
</tr>
<tr class="odd">
<td><strong>EFS</strong></td>
<td>Managed NFS</td>
<td>Multi-instance shared file system <strong>inside AWS</strong></td>
</tr>
<tr class="even">
<td><strong>FSx</strong></td>
<td>Managed file (Windows/Lustre/…)</td>
<td>Specific file-system software needs</td>
</tr>
<tr class="odd">
<td><strong>EBS</strong></td>
<td>Block</td>
<td>A disk <strong>attached to one EC2 instance</strong></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>A note on EBS sizing:</strong> with the older <strong>gp2</strong>, IOPS scaled with volume size, so you over-provisioned capacity to buy performance. <strong>gp3 decouples them</strong> — a baseline 3,000 IOPS regardless of size, with IOPS and throughput provisioned independently. Prefer gp3 for new volumes.</p>
</blockquote>
<p>More on storage classes, durability and lifecycle: <a href="./05-storage.html">05. Storage</a>.</p>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> When the requirement is <em>“keep NFS but store in AWS,”</em> <strong>S3 File Gateway</strong> is the purpose-built answer — local cache for latency, S3 for durability and lifecycle, and a clean path to native S3 later. Just be explicit that the upload is asynchronous.</p>
</blockquote>
<hr>
</section>
<section id="sec-operate" class="level2">
<h2 class="anchored" data-anchor-id="sec-operate">12.7 Step 6 — Operate one way across both environments</h2>
<blockquote class="blockquote">
<ul>
<li>❓ The customer wants the <strong>same tooling</strong> on-prem and in AWS. What makes that possible — and where does it stop?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    GOAL["Consistent operations&lt;br&gt;across DC and AWS"] --&gt; ECSA["Amazon ECS Anywhere&lt;br&gt;run ECS-managed containers&lt;br&gt;on your own hardware"]
    GOAL --&gt; SSM["AWS Systems Manager&lt;br&gt;Run Command, Patch,&lt;br&gt;Parameter Store, Maintenance Windows"]
    GOAL --&gt; BKP["AWS Backup&lt;br&gt;centralised, policy-based&lt;br&gt;protection across AWS and on-prem"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>ECS Anywhere</strong> runs and manages containers on <strong>customer-managed infrastructure</strong> using the <strong>same ECS APIs, scheduling and monitoring</strong> — it needs the <strong>ECS + SSM agents</strong> installed on local servers, plus outbound connectivity to AWS.</li>
<li><strong>AWS Systems Manager</strong> gives one control plane: <strong>Run Command</strong> (scripts across fleets without SSH), <strong>Patch Manager</strong>, <strong>Maintenance Windows</strong>, and <strong>Parameter Store</strong> (config/secrets, KMS-encrypted SecureStrings). Requires the <strong>SSM Agent</strong> on managed nodes.</li>
<li><strong>AWS Backup</strong> centralises and automates <strong>policy-based</strong> data protection across EC2, EBS, RDS/Aurora, DynamoDB, EFS/FSx, <strong>Storage Gateway volumes, and on-prem VMware</strong> — one place for compliance.</li>
</ul>
<blockquote class="blockquote">
<p><strong>⚠️ “Same tooling” has limits — say them out loud.</strong> ECS Anywhere external instances register with the <strong><code>EXTERNAL</code> launch type</strong> and do <strong>not</strong> support <code>awsvpc</code> task networking, <strong>Elastic Load Balancing target-group registration</strong>, or Fargate. So on-prem tasks are managed by the same control plane but are <strong>not operationally identical</strong> to cloud tasks — you still need a local load-balancing story. Also, the on-prem side depends on <strong>outbound connectivity to AWS</strong>: if the link drops, running containers keep running, but you lose orchestration.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Hybrid operational consistency comes from three pillars — <strong>ECS Anywhere</strong> (same container tooling), <strong>Systems Manager</strong> (same ops/automation), <strong>AWS Backup</strong> (same protection policy) — all reaching <em>into</em> the data centre via agents. Consistent control plane, not identical capability.</p>
</blockquote>
<hr>
</section>
<section id="sec-observability" class="level2">
<h2 class="anchored" data-anchor-id="sec-observability">12.8 Step 7 — Observe both sides through one pane</h2>
<blockquote class="blockquote">
<ul>
<li>❓ Half the estate has no AWS API in front of it. How do you monitor it the same way?</li>
</ul>
</blockquote>
<p>In a hybrid estate the <strong>link itself</strong> is the component most likely to hurt you and least likely to be watched. Instrument it first.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    DXm["Direct Connect&lt;br&gt;+ VPN tunnels"] --&gt; CW["Amazon CloudWatch&lt;br&gt;metrics, logs, alarms"]
    ECSm["ECS cluster + services"] --&gt; CW
    RDSm["RDS Multi-AZ&lt;br&gt;+ read replicas"] --&gt; CW
    SGWm["S3 File Gateway"] --&gt; CW
    DMSm["DMS replication task"] --&gt; CW
    ONP["On-prem servers&lt;br&gt;CloudWatch agent via SSM"] --&gt; CW
    CW --&gt; AL["Alarms to SNS&lt;br&gt;on-call notification"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Signals worth alarming on</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Metric</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Direct Connect</td>
<td><code>ConnectionState</code>, virtual-interface <strong>BGP state</strong></td>
<td>The earliest, cleanest “the link is gone” signal</td>
</tr>
<tr class="even">
<td>Direct Connect</td>
<td><code>ConnectionBpsEgress/Ingress</code>, <code>ConnectionErrorCount</code></td>
<td>Saturation and physical errors before users notice</td>
</tr>
<tr class="odd">
<td>Site-to-Site VPN</td>
<td><code>TunnelState</code></td>
<td>Confirms the failover path is actually up <em>before</em> you need it</td>
</tr>
<tr class="even">
<td>ECS</td>
<td>Container Insights, <code>CPUReservation</code>, <code>MemoryReservation</code>, running vs desired task count</td>
<td>Desired ≠ running means the cluster can’t place tasks</td>
</tr>
<tr class="odd">
<td>RDS</td>
<td><code>ReplicaLag</code>, <code>FreeStorageSpace</code>, <code>DatabaseConnections</code>, failover events</td>
<td>Replica lag silently makes reports wrong</td>
</tr>
<tr class="even">
<td>S3 File Gateway</td>
<td><code>CachePercentDirty</code>, <code>CloudBytesUploaded</code>, <code>FilesFailingUpload</code></td>
<td>Rising dirty cache = the async upload is falling behind (your RPO growing)</td>
</tr>
<tr class="odd">
<td>DMS</td>
<td><code>CDCLatencySource</code>, <code>CDCLatencyTarget</code></td>
<td>Tells you whether cutover is safe yet</td>
</tr>
</tbody>
</table>
<p><strong>Practices</strong></p>
<ul>
<li>Install the <strong>CloudWatch agent on-prem</strong> via <strong>Systems Manager hybrid activations</strong> so data-centre servers publish the <em>same</em> metrics and logs as EC2 — this is what makes “one pane of glass” real rather than aspirational.</li>
<li>Alarm on <strong><code>TunnelState</code> of the standby VPN</strong>, not just the primary link. An untested failover path is not a failover path.</li>
<li>Treat <strong>desired-vs-running task count</strong> as your container liveness check on both sides.</li>
</ul>
<p>See <a href="./07-monitoring.html">07. Monitoring</a> for CloudWatch fundamentals.</p>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> In hybrid, monitor the <strong>seam</strong>. BGP state, tunnel state and gateway upload lag are the metrics that tell you the two halves are still one system.</p>
</blockquote>
<hr>
</section>
<section id="sec-scale" class="level2">
<h2 class="anchored" data-anchor-id="sec-scale">12.9 Step 8 — Scale the moving parts</h2>
<blockquote class="blockquote">
<ul>
<li>❓ With ECS on EC2, what exactly scales, and how?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    subgraph ECS["Two scaling layers"]
        L1["Cluster Auto Scaling&lt;br&gt;EC2 instances"] --&gt;|"capacity provider +&lt;br&gt;CloudWatch metrics"| ASG["Auto Scaling group"]
        L2["Service Auto Scaling&lt;br&gt;task count"] --&gt;|"Application Auto Scaling"| TASK["Desired tasks up or down"]
    end
    CW["CloudWatch alarms"] --&gt; L1
    CW --&gt; L2
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>Cluster auto scaling</strong> grows/shrinks the <strong>EC2 fleet</strong> via an Auto Scaling group <strong>capacity provider</strong> with managed scaling.</li>
<li><strong>Service auto scaling</strong> grows/shrinks the <strong>number of tasks</strong> using <strong>Application Auto Scaling</strong>, driven by CloudWatch alarms.
<ul>
<li><strong>Target tracking</strong> (recommended) — like a thermostat: pick a metric target, AWS maintains it.</li>
<li><strong>Step scaling</strong> — adjustments sized to the alarm breach.</li>
</ul></li>
<li>Don’t forget the DB: <strong>RDS Storage Auto Scaling</strong> for storage growth.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> With the EC2 launch type you own <strong>two</strong> scaling dimensions — <strong>cluster (hosts)</strong> and <strong>service (tasks)</strong>. Prefer <strong>target-tracking</strong> policies. This is operational work you would <em>not</em> pay with Fargate, and it belongs in the EC2-vs-Fargate trade-off.</p>
</blockquote>
<hr>
</section>
<section id="sec-dr" class="level2">
<h2 class="anchored" data-anchor-id="sec-dr">12.10 Step 9 — Design for disaster recovery</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How much resilience does an enterprise workload need — and what does each level cost?</li>
</ul>
</blockquote>
<p>DR strategies sit on a spectrum from <strong>cheap/slow</strong> to <strong>expensive/instant</strong>. The choice is an <strong>RTO/RPO vs cost/complexity</strong> trade-off.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    BR["Backup and Restore&lt;br&gt;lowest cost&lt;br&gt;highest RTO"] --&gt; PL["Pilot Light&lt;br&gt;core infra on,&lt;br&gt;rest off"]
    PL --&gt; WS["Warm Standby&lt;br&gt;scaled-down but&lt;br&gt;always running"]
    WS --&gt; MS["Multi-site Active/Active&lt;br&gt;highest cost&lt;br&gt;near-zero RTO"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>What’s running in the recovery Region</th>
<th>RTO/RPO</th>
<th>Cost &amp; complexity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Backup &amp; restore</strong></td>
<td>Nothing; redeploy from backups + <strong>IaC</strong></td>
<td>Hours</td>
<td>Lowest</td>
</tr>
<tr class="even">
<td><strong>Pilot light</strong></td>
<td>Core (DB replication, storage) <strong>on</strong>; app servers <strong>off</strong></td>
<td>Lower</td>
<td>Low–medium</td>
</tr>
<tr class="odd">
<td><strong>Warm standby</strong></td>
<td>Scaled-down but <strong>fully functional</strong> copy always on</td>
<td>Minutes</td>
<td>Medium</td>
</tr>
<tr class="even">
<td><strong>Multi-site active/active</strong></td>
<td>Full capacity serving traffic in all Regions</td>
<td><strong>Near zero</strong></td>
<td>Highest</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Active/passive</strong> (backup/restore, pilot light, warm standby) recovers <strong>into</strong> a passive site; <strong>active/active</strong> serves from <strong>all</strong> Regions.</li>
<li><strong>IaC (CloudFormation / CDK)</strong> is essential for fast, error-free redeploy — also back up <strong>code, config and AMIs</strong>, and automate redeploy with <strong>CodePipeline</strong>.</li>
</ul>
<p>Active-active vs active-passive topologies are covered further in <a href="./08-optimization.html">08. Optimization</a>.</p>
<p><strong>Make the network itself resilient</strong> — back <strong>Direct Connect</strong> with a <strong>Site-to-Site VPN</strong>:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    DCn["Data Center"] --&gt;|"primary dedicated"| DX["AWS Direct Connect"]
    DCn -.-&gt;|"failover IPsec"| VPN["Site-to-Site VPN"]
    DX --&gt; AWS["AWS VPC"]
    VPN -.-&gt; AWS
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Pick the <strong>cheapest DR strategy that still meets your RTO/RPO</strong> — most enterprises land on <strong>warm standby</strong> unless near-zero downtime justifies <strong>active/active</strong>. And never leave the <strong>link</strong> as a SPOF: back <strong>Direct Connect</strong> with a <strong>VPN</strong>, while remembering the bandwidth cliff from <a href="#sec-connect">12.3.3</a>.</p>
</blockquote>
<hr>
</section>
<section id="sec-reference" class="level2">
<h2 class="anchored" data-anchor-id="sec-reference">12.11 The reference architecture, end to end</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph DCn["On-Premises"]
        OC["Containers&lt;br&gt;ECS Anywhere"]
        ODB["PostgreSQL"]
        OFS["Apps over NFS"]
        SGW["S3 File Gateway&lt;br&gt;local cache"]
        OFS --&gt; SGW
    end

    DCn &lt;==&gt;|"Direct Connect&lt;br&gt;plus VPN failover"| AWS

    subgraph AWS["AWS Cloud VPC"]
        subgraph A1["AZ 1"]
            ECS1["ECS on EC2&lt;br&gt;private subnet"] --&gt; NAT1["NAT gateway 1"]
        end
        subgraph A2["AZ 2"]
            ECS2["ECS on EC2&lt;br&gt;private subnet"] --&gt; NAT2["NAT gateway 2"]
        end
        VPE["VPC endpoints&lt;br&gt;ECR, SSM, S3, Logs"]
        RDS["RDS PostgreSQL&lt;br&gt;Multi-AZ + read replica"]
        S3["Amazon S3&lt;br&gt;Intelligent-Tiering"]
        ECS1 --&gt; RDS
        ECS2 --&gt; RDS
        ECS1 -.-&gt; VPE
        ECS2 -.-&gt; VPE
        SGW -.-&gt;|async| S3
    end

    ODB -.-&gt;|"DMS data + pg_dump schema"| RDS
    OPS["ECS Anywhere · Systems Manager · AWS Backup"] -.-&gt; DCn
    OPS -.-&gt; AWS
    CW["CloudWatch: BGP state, tunnel state,&lt;br&gt;task counts, replica lag, cache lag"] -.-&gt; AWS
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>How each driver is satisfied</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Driver</th>
<th>Where it is met</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dedicated, consistent connectivity</td>
<td><strong>Direct Connect</strong> (+ MACsec or IPsec if encryption required), VPN failover</td>
</tr>
<tr class="even">
<td>Private containers, outbound only</td>
<td><strong>Private subnets + NAT gateway per AZ + VPC endpoints</strong></td>
</tr>
<tr class="odd">
<td>Custom AMI + host access</td>
<td><strong>ECS EC2 launch type</strong></td>
</tr>
<tr class="even">
<td>Same tooling both sides</td>
<td><strong>ECS Anywhere, Systems Manager, AWS Backup</strong></td>
</tr>
<tr class="odd">
<td>No-rewrite DB migration</td>
<td><strong>RDS PostgreSQL + DMS</strong> (schema via <code>pg_dump</code>)</td>
</tr>
<tr class="even">
<td>High availability</td>
<td><strong>RDS Multi-AZ</strong>, redundant links, <strong>multi-AZ NAT</strong>, multi-AZ ECS</td>
</tr>
<tr class="odd">
<td>NFS access to AWS data</td>
<td><strong>S3 File Gateway → S3</strong></td>
</tr>
<tr class="even">
<td>Observability</td>
<td><strong>CloudWatch</strong> across both sides via the SSM-installed agent</td>
</tr>
<tr class="odd">
<td>Cost efficiency</td>
<td><strong>VPC endpoints</strong> instead of NAT egress, <strong>S3 Intelligent-Tiering</strong></td>
</tr>
<tr class="even">
<td>Resilience / DR</td>
<td><strong>Warm standby</strong> (or chosen tier) + IaC</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="sec-not" class="level2">
<h2 class="anchored" data-anchor-id="sec-not">12.12 When <em>not</em> to use these choices</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symptom</th>
<th>Reconsider</th>
<th>Better fit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No custom AMI / no host access needed</td>
<td>EC2 launch type</td>
<td><strong>Fargate</strong> (drop the cluster ops)</td>
</tr>
<tr class="even">
<td>Low-volume or temporary connectivity</td>
<td>Direct Connect</td>
<td><strong>Site-to-Site VPN</strong> (cheaper, quick, no lead time)</td>
</tr>
<tr class="odd">
<td>Migration deadline shorter than DX provisioning</td>
<td>Dedicated connection</td>
<td><strong>Hosted connection</strong> via a partner, or VPN first</td>
</tr>
<tr class="even">
<td>Only 1 VPC, 1 account</td>
<td>Transit Gateway</td>
<td>Direct connection / simple peering</td>
</tr>
<tr class="odd">
<td>Shared file system <strong>inside</strong> AWS only</td>
<td>S3 File Gateway</td>
<td><strong>Amazon EFS</strong></td>
</tr>
<tr class="even">
<td>Heterogeneous DB engines</td>
<td>One-step DMS</td>
<td><strong>DMS + AWS SCT</strong> (schema conversion)</td>
</tr>
<tr class="odd">
<td>On-prem tasks need ELB / <code>awsvpc</code> networking</td>
<td>ECS Anywhere</td>
<td>Local orchestration, or move the workload to AWS</td>
</tr>
<tr class="even">
<td>Near-zero RTO mandated + budget</td>
<td>Warm standby</td>
<td><strong>Multi-site active/active</strong></td>
</tr>
<tr class="odd">
<td>Read scaling needed, not availability</td>
<td>Multi-AZ standby</td>
<td><strong>Read replicas</strong> (and vice-versa)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Every choice here flips with a change in <strong>volume, tooling needs, engine compatibility, provisioning time, or RTO budget</strong>. “Best fit” = technical + operational + cost, across <strong>both</strong> environments.</p>
</blockquote>
<hr>
</section>
<section id="sec-cheatsheet" class="level2">
<h2 class="anchored" data-anchor-id="sec-cheatsheet">12.13 Architect’s cheat sheet</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    ROOT["Hybrid container&lt;br&gt;workload on AWS"]

    ROOT --&gt; N["Network"]
    N --&gt; N1["Direct Connect = consistent, private, high-volume"]
    N --&gt; N2["DX is NOT encrypted by default"]
    N --&gt; N3["DX has weeks-to-months lead time"]
    N --&gt; N4["Transit Gateway + DX Gateway = many VPCs"]

    ROOT --&gt; C["Compute"]
    C --&gt; C1["ECS on EC2 = custom AMI + SSH"]
    C --&gt; C2["Fargate = no host, no custom AMI"]
    C --&gt; C3["One NAT gateway PER AZ"]
    C --&gt; C4["VPC endpoints beat NAT for AWS traffic"]

    ROOT --&gt; D["Database"]
    D --&gt; D1["RDS PostgreSQL = lift-and-shift"]
    D --&gt; D2["Multi-AZ = availability; endpoint stable"]
    D --&gt; D3["Read replica = read scaling, async"]
    D --&gt; D4["DMS moves data, not full schema"]

    ROOT --&gt; S["Storage + Ops"]
    S --&gt; S1["S3 File Gateway = NFS local, S3 behind"]
    S --&gt; S2["ECS Anywhere + SSM + Backup"]
    S --&gt; S3["Watch BGP state and tunnel state"]
    S --&gt; S4["DR: cheapest tier that meets RTO/RPO"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ol type="1">
<li>In hybrid design the <strong>network is the foundation</strong> — decide connectivity first.</li>
<li>Agree <strong>non-overlapping CIDR ranges</strong> between data centre and VPC before anything else.</li>
<li><strong>Direct Connect</strong> for consistent, dedicated, high-volume DC↔︎AWS traffic (off the public internet).</li>
<li><strong>Direct Connect is private, not encrypted</strong> — add <strong>MACsec</strong> or an <strong>IPsec VPN over DX</strong> if compliance requires it.</li>
<li><strong>Direct Connect takes weeks to months</strong> to provision; use a <strong>hosted connection</strong> or VPN to bridge a deadline.</li>
<li>Always add a <strong>VPN failover</strong> for Direct Connect — a single link is a SPOF; without backup, VPC traffic drops.</li>
<li><strong>VPN failover is survival, not capacity</strong>: ~1.25 Gbps per tunnel. Two DX at two locations is the real HA answer.</li>
<li><strong>Site-to-Site VPN</strong> = cheap/quick or failover; <strong>Client VPN</strong> = remote workforce access.</li>
<li><strong>Transit Gateway</strong> turns an unmanageable VPC <strong>mesh</strong> into a <strong>hub</strong>; a <strong>Direct Connect Gateway</strong> reaches many VPCs/Regions.</li>
<li><strong>ECS on EC2</strong> when you need a <strong>custom AMI</strong> or <strong>SSH</strong>; <strong>Fargate</strong> can’t do either.</li>
<li>Private subnets + <strong>managed NAT gateway</strong> = <strong>outbound-only</strong> internet; no unsolicited inbound.</li>
<li><strong>A NAT gateway is AZ-scoped — deploy one per AZ</strong>, or you have re-created the SPOF you were told to remove.</li>
<li>Use <strong>VPC endpoints</strong> (S3 gateway; ECR/SSM/Logs interface) to cut NAT data-processing cost and stay off the internet.</li>
<li><strong>RDS + managed engine</strong> = lift-and-shift with <strong>no app rewrite</strong>.</li>
<li><strong>Multi-AZ DB instance = availability</strong> (synchronous, non-readable standby, auto-failover, <strong>endpoint unchanged</strong>).</li>
<li><strong>Multi-AZ DB cluster</strong> (PostgreSQL/MySQL) = two <strong>readable</strong> standbys, ~<strong>35 s</strong> failover, ~2× faster commits.</li>
<li><strong>Read replica = performance</strong> (asynchronous, read-only, replica lag). Don’t confuse it with a standby.</li>
<li>Scale RDS by the <strong>right axis</strong>: vertical (CPU+storage), replicas (read CPU), <strong>Storage Auto Scaling</strong>, Provisioned IOPS.</li>
<li><strong>DMS migrates data, not full schema</strong> — no secondary indexes, sequences, FKs or procedures. Use <code>pg_dump</code>/<code>pg_restore</code> for schema.</li>
<li><strong>CDC from PostgreSQL needs logical replication</strong> enabled on the source <em>before</em> cutover.</li>
<li><strong>S3 File Gateway</strong> = keep <strong>NFS/SMB</strong> locally with a <strong>cache</strong>, store in <strong>S3</strong> async — no app refactor.</li>
<li>File Gateway upload is <strong>asynchronous</strong> (real RPO), and out-of-band bucket writes need <strong><code>RefreshCache</code></strong>.</li>
<li>Know the storage menu: <strong>S3</strong> (object), <strong>EFS</strong> (cloud NFS), <strong>FSx</strong> (specific FS), <strong>EBS</strong> (block); prefer <strong>gp3</strong>, which decouples IOPS from size.</li>
<li><strong>ECS Anywhere</strong> runs ECS-managed containers on your <strong>own hardware</strong> — but no <code>awsvpc</code>, no ELB target groups, no Fargate.</li>
<li><strong>Systems Manager</strong> (Run Command, Patch, Parameter Store) + <strong>AWS Backup</strong> centralise hybrid ops and protection.</li>
<li>Install the <strong>CloudWatch agent on-prem via SSM hybrid activations</strong> — that is what makes one pane of glass real.</li>
<li><strong>Monitor the seam:</strong> DX <code>ConnectionState</code>/BGP, VPN <code>TunnelState</code>, gateway <code>CachePercentDirty</code>, DMS CDC latency.</li>
<li>ECS on EC2 has <strong>two</strong> scaling layers: <strong>cluster (hosts)</strong> and <strong>service (tasks)</strong> — prefer <strong>target tracking</strong>.</li>
<li><strong>DR spectrum:</strong> backup/restore → pilot light → warm standby → active/active (cost ↑, RTO ↓); use <strong>IaC</strong> for redeploy.</li>
<li>“Serverless by default” is not a law — <strong>ECS on EC2</strong> here proves fit beats fashion.</li>
</ol>
<hr>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<p><em>Inspired from course notes — “Architecting Solutions on AWS”, Week 3: Designing a Hybrid Solution for Container-Based Workloads (enterprise container + PostgreSQL migration use case).</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-serverless-data-analytics.html" class="pagination-link" aria-label="11. Architecting Serverless Data Analytics Solutions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">11. Architecting Serverless Data Analytics Solutions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./13-multi-account-strategies.html" class="pagination-link" aria-label="13. Architecting for Account Governance and Multi-Account Management">
        <span class="nav-page-text"><span class="chapter-title">13. Architecting for Account Governance and Multi-Account Management</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>