<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Senthil Kumar">

<title>14. Capstone Project: Decoupling a Three-Tier App and Migrating Hadoop Analytics with Amazon EMR – Foundational Questions. Visual Answers. Mastering AWS Fundamentals.</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-multi-account-strategies.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81dce849c25865aa69203cbf510b76f1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-architecting-serverless-backend-solution-in-aws.html">Architecting Solutions in AWS</a></li><li class="breadcrumb-item"><a href="./14-capstone-decoupled-app-and-emr-analytics.html"><span class="chapter-title">14. Capstone Project: Decoupling a Three-Tier App and Migrating Hadoop Analytics with Amazon EMR</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundational Questions. Visual Answers. Mastering AWS Fundamentals.</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Foundational Questions. Visual Answers. Mastering AWS Fundamentals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Introduction to AWS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-security.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">02. Security</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-compute.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">03. Compute</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-networking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">04. Networking</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-storage.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">05. Storage</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-databases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">06. Databases</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-monitoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">07. Monitoring</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">08. Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-references-disclosure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">09.Disclosure</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Architecting Solutions in AWS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-architecting-serverless-backend-solution-in-aws.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Architecting a Serverless Web Backend</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-serverless-data-analytics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Architecting Serverless Data Analytics Solutions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-hybrid-container-workloads.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. Architecting Hybrid Container-Based Workloads</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-multi-account-strategies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Architecting for Account Governance and Multi-Account Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-capstone-decoupled-app-and-emr-analytics.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">14. Capstone Project: Decoupling a Three-Tier App and Migrating Hadoop Analytics with Amazon EMR</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#capstone-one-customer-two-workloads-one-migration" id="toc-capstone-one-customer-two-workloads-one-migration" class="nav-link active" data-scroll-target="#capstone-one-customer-two-workloads-one-migration">Capstone: One Customer, Two Workloads, One Migration</a></li>
  <li><a href="#the-method-one-estate-two-tracks" id="toc-the-method-one-estate-two-tracks" class="nav-link" data-scroll-target="#the-method-one-estate-two-tracks">14.1 The Method: one estate, two tracks</a></li>
  <li><a href="#sec-drivers" id="toc-sec-drivers" class="nav-link" data-scroll-target="#sec-drivers">14.2 Turn requirements into architectural drivers</a></li>
  <li><a href="#sec-frontend" id="toc-sec-frontend" class="nav-link" data-scroll-target="#sec-frontend">14.3 Decouple the frontend</a></li>
  <li><a href="#sec-backend" id="toc-sec-backend" class="nav-link" data-scroll-target="#sec-backend">14.4 Decouple the backend compute</a></li>
  <li><a href="#sec-database" id="toc-sec-database" class="nav-link" data-scroll-target="#sec-database">14.5 Decouple and migrate the database</a></li>
  <li><a href="#sec-ingest" id="toc-sec-ingest" class="nav-link" data-scroll-target="#sec-ingest">14.6 Ingest the analytics data into AWS</a></li>
  <li><a href="#sec-emr" id="toc-sec-emr" class="nav-link" data-scroll-target="#sec-emr">14.7 Process the workload with Amazon EMR</a>
  <ul class="collapse">
  <li><a href="#emr-cluster-shape-transient-not-persistent" id="toc-emr-cluster-shape-transient-not-persistent" class="nav-link" data-scroll-target="#emr-cluster-shape-transient-not-persistent">14.7.1 EMR cluster shape: transient, not persistent</a></li>
  <li><a href="#emr-node-types-and-how-they-read-s3" id="toc-emr-node-types-and-how-they-read-s3" class="nav-link" data-scroll-target="#emr-node-types-and-how-they-read-s3">14.7.2 EMR node types and how they read S3</a></li>
  <li><a href="#why-not-emr-serverless-or-emr-on-eks-here" id="toc-why-not-emr-serverless-or-emr-on-eks-here" class="nav-link" data-scroll-target="#why-not-emr-serverless-or-emr-on-eks-here">14.7.3 Why not EMR Serverless or EMR on EKS here</a></li>
  </ul></li>
  <li><a href="#sec-query" id="toc-sec-query" class="nav-link" data-scroll-target="#sec-query">14.8 Catalog and query the lake</a></li>
  <li><a href="#sec-visualise" id="toc-sec-visualise" class="nav-link" data-scroll-target="#sec-visualise">14.9 Visualise the insight</a></li>
  <li><a href="#sec-secure" id="toc-sec-secure" class="nav-link" data-scroll-target="#sec-secure">14.10 Secure both tracks</a></li>
  <li><a href="#sec-observability" id="toc-sec-observability" class="nav-link" data-scroll-target="#sec-observability">14.11 Make both tracks observable</a></li>
  <li><a href="#sec-resilient" id="toc-sec-resilient" class="nav-link" data-scroll-target="#sec-resilient">14.12 Cut over safely, and control cost</a></li>
  <li><a href="#sec-reference" id="toc-sec-reference" class="nav-link" data-scroll-target="#sec-reference">14.13 The reference architecture, end to end</a></li>
  <li><a href="#sec-not" id="toc-sec-not" class="nav-link" data-scroll-target="#sec-not">14.14 When <em>not</em> to build it this way</a></li>
  <li><a href="#sec-cheatsheet" id="toc-sec-cheatsheet" class="nav-link" data-scroll-target="#sec-cheatsheet">14.15 Architect’s cheat sheet</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources">Sources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-architecting-serverless-backend-solution-in-aws.html">Architecting Solutions in AWS</a></li><li class="breadcrumb-item"><a href="./14-capstone-decoupled-app-and-emr-analytics.html"><span class="chapter-title">14. Capstone Project: Decoupling a Three-Tier App and Migrating Hadoop Analytics with Amazon EMR</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">14. Capstone Project: Decoupling a Three-Tier App and Migrating Hadoop Analytics with Amazon EMR</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Senthil Kumar </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>👈 <strong>Back to:</strong> <a href="https://senthilkumarm1901.github.io/learn_by_blogging/blog.html">📝 Blog</a> | <a href="https://www.linkedin.com/in/senthilkumarm1901">💼 LinkedIn</a> | <a href="https://medium.com/@senthilkumar.m1901">✍️ Medium</a></p>
<hr>
<section id="capstone-one-customer-two-workloads-one-migration" class="level2">
<h2 class="anchored" data-anchor-id="capstone-one-customer-two-workloads-one-migration">Capstone: One Customer, Two Workloads, One Migration</h2>
<ul>
<li>❓ Key question of this chapter:
<ul>
<li>When a customer hands you <strong>two</strong> on-premises workloads at once:
<ul>
<li>a three-tier web app <em>and</em> a Hadoop analytics estate and</li>
<li>tells you to decouple one and re-platform the other onto <strong>Amazon EMR</strong></li>
</ul></li>
<li>how do you design both without one decision quietly breaking the other?</li>
</ul></li>
<li><ul>
<li>Workflow followed in all chapters: <strong>requirements → architectural drivers → candidate services → trade-offs → decision → justified rejections</strong>.</li>
</ul></li>
<li>What’s new is that this chapter: Learnings from 3 previous chapters applied at once
<ul>
<li>it reuses the decoupling pattern from Chapter 10,</li>
<li>the ingest→store→query→visualise pipeline from Chapter 11, and</li>
<li>the lift-and-shift database pattern from Chapter 12</li>
</ul></li>
</ul>
<p><strong>Running example used throughout this chapter</strong></p>
<blockquote class="blockquote">
<p>A customer runs two workloads <strong>on physical servers in one data centre</strong>:</p>
<ol type="1">
<li>A <strong>three-tier web application</strong>: a static frontend (HTML/CSS/JavaScript), a backend (Apache + a Java application), and a <strong>MySQL</strong> database — serving a public dynamic website. Today all three tiers live on the <strong>same physical servers</strong>.</li>
<li>A <strong>Hadoop analytics workload</strong>: a massive on-premises dataset processed by a physical Hadoop cluster, with visualisation tools on top.</li>
</ol>
<p><strong>The problem the customer actually has:</strong> everything shares one data centre and one power supply. <strong>A single power outage takes down the website <em>and</em> the analytics estate at the same time.</strong></p>
<ul>
<li><p><strong>Goal:</strong> migrate both workloads to AWS.</p></li>
<li><p><strong>Decouple</strong> the web app’s three layers so no single failure or single server takes down the whole site.</p></li>
<li><p>Host the analytics workload in the cloud too, with an explicit requirement to <strong>run it on an Amazon EMR cluster</strong>.</p></li>
<li><p>Ingestion, storage and visualisation choices for the analytics side are ours to make.</p></li>
<li><p><em>In scope:</em> re-platforming the three tiers and the analytics pipeline onto AWS.</p></li>
<li><p><em>Out of scope:</em> rewriting the Java application’s business logic or the Hadoop jobs’ code.</p></li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    subgraph OnPrem["On-premises today&lt;br&gt;one data centre, one power feed"]
        FE1["Frontend&lt;br&gt;HTML/CSS/JS"] --&gt; BE1["Backend&lt;br&gt;Apache + Java"]
        BE1 --&gt; DB1[("MySQL")]
        HAD["Hadoop cluster&lt;br&gt;+ visualisation tools"]
    end
    OnPrem --&gt;|"decouple + migrate"| Cloud

    subgraph Cloud["Goal: on AWS"]
        FE2["Frontend tier"]
        BE2["Backend tier"]
        DB2[("Database tier")]
        EMR2["EMR analytics&lt;br&gt;tier"]
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="the-method-one-estate-two-tracks" class="level2">
<h2 class="anchored" data-anchor-id="the-method-one-estate-two-tracks">14.1 The Method: one estate, two tracks</h2>
<p>Both workloads answer the <strong>same four questions</strong> * <em>what talks to what, </em> where does compute run, * where does state live, * how is it observed and secured* <br> But the analytics track has one constraint fixed in advance: * <strong>it must use Amazon EMR</strong>. * That single fixed point shapes every other analytics decision in this chapter, the same way “short-staffed” shaped Chapter 11.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    A["1. Decouple&lt;br&gt;the app tiers"] --&gt; B["2. Migrate the&lt;br&gt;database"]
    B --&gt; C["3. Ingest analytics&lt;br&gt;data to AWS"]
    C --&gt; D["4. Process with&lt;br&gt;Amazon EMR"]
    D --&gt; E["5. Query and&lt;br&gt;visualise"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Question the architect answers</th>
<th>Winning service(s)</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>What are the real <strong>architectural drivers</strong>?</td>
<td>—</td>
<td><a href="#sec-drivers">14.2</a></td>
</tr>
<tr class="even">
<td>2</td>
<td><strong>Client Tier</strong>: How does the frontend become independent?</td>
<td><strong>Amazon S3 + CloudFront</strong></td>
<td><a href="#sec-frontend">14.3</a></td>
</tr>
<tr class="odd">
<td>3</td>
<td><strong>Backend Tier</strong>: Where does the Java backend run, decoupled?</td>
<td><strong>Amazon ECS on Fargate</strong> + ALB</td>
<td><a href="#sec-backend">14.4</a></td>
</tr>
<tr class="even">
<td>4</td>
<td><strong>Database Tier</strong>: How does MySQL move, without a rewrite?</td>
<td><strong>Amazon RDS for MySQL</strong> + <strong>AWS DMS</strong></td>
<td><a href="#sec-database">14.5</a></td>
</tr>
<tr class="odd">
<td>5</td>
<td><strong>Ingestion</strong>: How does the Hadoop dataset get into AWS?</td>
<td><strong>AWS DataSync</strong> (+ <strong>Snowball</strong> for the bulk seed)</td>
<td><a href="#sec-ingest">14.6</a></td>
</tr>
<tr class="even">
<td>6</td>
<td><strong>Transformation/Processing</strong>: How is it processed — on the mandated EMR?</td>
<td><strong>Amazon EMR</strong>, transient, reading from <strong>S3 via EMRFS</strong></td>
<td><a href="#sec-emr">14.7</a></td>
</tr>
<tr class="odd">
<td>7</td>
<td><strong>Querying</strong>: How do we query it with SQL?</td>
<td><strong>AWS Glue Data Catalog + Amazon Athena</strong></td>
<td><a href="#sec-query">14.8</a></td>
</tr>
<tr class="even">
<td>8</td>
<td><strong>Visualization</strong>: How do business users see it?</td>
<td><strong>Amazon QuickSight</strong></td>
<td><a href="#sec-visualise">14.9</a></td>
</tr>
<tr class="odd">
<td>9</td>
<td>How is every hop <strong>secured</strong>?</td>
<td>IAM + KMS + Security Groups + WAF</td>
<td><a href="#sec-secure">14.10</a></td>
</tr>
<tr class="even">
<td>10</td>
<td><strong>Monitoring</strong>: How do we see what’s happening, on both tracks?</td>
<td><strong>Amazon CloudWatch</strong></td>
<td><a href="#sec-observability">14.11</a></td>
</tr>
<tr class="odd">
<td>11</td>
<td><strong>Optimization</strong>: How do we cut over safely, and control cost?</td>
<td>DMS CDC cutover, Spot task nodes, S3 lifecycle</td>
<td><a href="#sec-resilient">14.12</a></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Treat this as <strong>two pipelines sharing one VPC and one security model</strong>, not one giant diagram. Every decision below is deliberately small and local — that is what makes a two-workload migration reviewable.</p>
</blockquote>
<hr>
</section>
<section id="sec-drivers" class="level2">
<h2 class="anchored" data-anchor-id="sec-drivers">14.2 Turn requirements into architectural drivers</h2>
<blockquote class="blockquote">
<ul>
<li>❓ “Decouple the app, EMR for analytics, and it’s up to you for the rest” — what does that actually constrain?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    R1["One data centre =&lt;br&gt;one blast radius"] --&gt; D1["Decouple every tier;&lt;br&gt;no shared failure domain"]
    R2["Public dynamic website"] --&gt; D2["Independent, scalable&lt;br&gt;frontend + backend"]
    R3["MySQL, no rewrite wanted"] --&gt; D3["Engine-compatible&lt;br&gt;managed database"]
    R4["Hadoop workload,&lt;br&gt;EMR mandated"] --&gt; D4["S3-backed, transient&lt;br&gt;EMR cluster"]
    R5["Ingestion/storage/viz&lt;br&gt;= architect's choice"] --&gt; D5["Reuse proven&lt;br&gt;ingest-store-query-visualise"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Customer requirement</th>
<th>Architectural driver</th>
<th>Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single data centre, single power domain</td>
<td><strong>Eliminate the shared failure domain</strong></td>
<td>Each tier becomes independently deployable and independently recoverable</td>
</tr>
<tr class="even">
<td>Public, dynamic three-tier website</td>
<td><strong>Decoupled, scalable app layers</strong></td>
<td>Frontend, backend and database each get their own AWS service, not one bigger server</td>
</tr>
<tr class="odd">
<td>MySQL, minimal appetite for code changes</td>
<td><strong>Engine compatibility over optimality</strong></td>
<td>A managed MySQL-compatible database, moved with a migration service, not a rewrite</td>
</tr>
<tr class="even">
<td>Hadoop workload, <strong>EMR is mandatory</strong></td>
<td><strong>Fixed compute engine for analytics</strong></td>
<td>Every ingestion/storage decision must feed EMR cleanly — no service that bypasses it</td>
</tr>
<tr class="odd">
<td>Free choice of ingestion, storage, visualisation</td>
<td><strong>Reuse a proven pipeline shape</strong></td>
<td>Ingest → store → process (EMR) → query → visualise, as in Chapter 11, with EMR replacing the ETL step</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>The refactor-vs-lift-and-shift decision, made explicit.</strong> This chapter deliberately takes a <strong>middle path</strong>, and states why for each tier:</p>
<ul>
<li><strong>Frontend — refactor (extract to S3 + CloudFront).</strong> The HTML/CSS/JS has no server-side logic; there is nothing to “rewrite”, only to relocate. This is the cheapest possible refactor with the biggest payoff: the frontend tier disappears as a maintenance burden entirely.</li>
<li><strong>Backend — moderate refactor (containerise, don’t rewrite).</strong> The Java application is <strong>packaged into a container image</strong>, not rewritten. This decouples it from a specific physical server and lets it scale independently, without touching business logic.</li>
<li><strong>Database — lift-and-shift (same engine, migrated).</strong> MySQL becomes <strong>Amazon RDS for MySQL</strong>. Wire protocol and SQL dialect are unchanged, so the application’s data-access code needs <strong>no changes</strong> at all.</li>
<li><strong>Analytics — mandated re-platform (EMR, not a rewrite of the jobs).</strong> The customer’s Hadoop/Spark jobs keep running on EMR’s Hadoop-compatible runtime; what changes is <strong>where the data lives</strong> (S3 instead of on-cluster HDFS), not the job code.</li>
</ul>
<p>This mirrors the assignment’s own framing: refactor where it is nearly free (frontend), refactor lightly where it buys resilience without rewriting logic (backend, analytics platform), and lift-and-shift where compatibility matters more than elegance (database engine).</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> “Decouple” and “EMR” are both non-negotiable constraints in this brief — the design freedom is entirely in <em>how</em> you satisfy them, not <em>whether</em>.</p>
</blockquote>
<hr>
</section>
<section id="sec-frontend" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontend">14.3 Decouple the frontend</h2>
<blockquote class="blockquote">
<ul>
<li>❓ The frontend is static HTML/CSS/JS living on the same server as the backend. What removes it as a shared point of failure?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    Q["Static HTML/CSS/JS,&lt;br&gt;today on the app server"] --&gt; Q1{"Any server-side&lt;br&gt;logic in these files?"}
    Q1 --&gt;|No| S3["Amazon S3 + CloudFront - CHOSEN&lt;br&gt;static hosting + global cache"]
    Q1 --&gt;|"Yes / dynamic pages"| BEOPT["Keep with the&lt;br&gt;backend tier instead"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: Amazon S3 for storage, Amazon CloudFront in front of it.</strong> Static assets have no reason to live on a compute instance at all. Moving them to S3 removes the frontend as a dependency of the backend’s uptime, and CloudFront caches them at edge locations close to users — lower latency, and far less load reaching the origin.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>How S3 + CloudFront meets it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No shared failure domain with the backend</td>
<td>S3 is independently durable (11 nines) and served without any EC2/container instance</td>
</tr>
<tr class="even">
<td>Public dynamic website, fast for users</td>
<td>CloudFront edge caching cuts latency versus serving every request from one Region</td>
</tr>
<tr class="odd">
<td>DDoS / basic web protection</td>
<td><strong>AWS WAF</strong> attaches to CloudFront in front of the origin</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> The frontend tier is the easiest win in this whole capstone — it costs nothing in refactor effort and removes an entire tier from the backend’s blast radius.</p>
</blockquote>
<hr>
</section>
<section id="sec-backend" class="level2">
<h2 class="anchored" data-anchor-id="sec-backend">14.4 Decouple the backend compute</h2>
<blockquote class="blockquote">
<ul>
<li>❓ The Java app runs on Apache on a physical server. How does it run on AWS without a full rewrite, while still being independently scalable?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    W["Java app + Apache,&lt;br&gt;today on a physical server"] --&gt; Q1{"Willing to&lt;br&gt;containerise?"}
    Q1 --&gt;|"Yes, no code rewrite"| ECS["Amazon ECS on Fargate - CHOSEN&lt;br&gt;serverless containers"]
    Q1 --&gt;|"No, keep as VMs"| EC2["EC2 Auto Scaling Group&lt;br&gt;viable, more to patch/manage"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: Amazon ECS on AWS Fargate</strong>, behind an <strong>Application Load Balancer</strong>. The Java application and Apache layer are packaged as a <strong>container image</strong> — a packaging change, not a code change — and Fargate removes the underlying EC2 fleet entirely, so there is no host patching to inherit from the old physical servers.</p>
<p><strong>Backend tier architecture</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    CF["CloudFront&lt;br&gt;frontend"] --&gt;|"dynamic requests"| ALB["Application&lt;br&gt;Load Balancer"]
    ALB --&gt; T1["ECS Fargate task&lt;br&gt;AZ 1"]
    ALB --&gt; T2["ECS Fargate task&lt;br&gt;AZ 2"]
    ASG["ECS Service&lt;br&gt;Auto Scaling"] -.-&gt; T1
    ASG -.-&gt; T2
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>ECS on Fargate (chosen)</th>
<th>EC2 Auto Scaling Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>You manage</td>
<td>Just the container and its task definition</td>
<td>AMIs, patching, capacity</td>
</tr>
<tr class="even">
<td>Rewrite required</td>
<td>No — container the existing app</td>
<td>No — same VM-based app</td>
</tr>
<tr class="odd">
<td>Independently scalable from DB/frontend</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Fit here</td>
<td>Team wants less host management going forward</td>
<td>Team wants to keep VM-level control</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> “Decoupled” does not require a rewrite. Packaging the existing Java app into a container and running it on Fargate behind an ALB satisfies the decoupling requirement with the smallest possible code change.</p>
</blockquote>
<hr>
</section>
<section id="sec-database" class="level2">
<h2 class="anchored" data-anchor-id="sec-database">14.5 Decouple and migrate the database</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How does MySQL move off the shared physical server with zero application code changes and no single point of failure?</li>
</ul>
</blockquote>
<p><strong>Chosen: Amazon RDS for MySQL, Multi-AZ, migrated with AWS DMS</strong> — the same lift-and-shift pattern used for PostgreSQL in <a href="./12-hybrid-container-workloads.html#sec-db">12.5</a>, applied here to MySQL.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    APP["ECS Fargate&lt;br&gt;backend"] --&gt; PRI["RDS for MySQL&lt;br&gt;Primary, AZ 1"]
    PRI --&gt;|"synchronous&lt;br&gt;replication"| STB["Standby&lt;br&gt;AZ 2"]
    SRC["On-prem MySQL"] --&gt; DMS["AWS DMS&lt;br&gt;replication task"]
    DMS --&gt;|"initial load +&lt;br&gt;ongoing changes"| PRI
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>How RDS + DMS meets it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No application rewrite</td>
<td>Same wire protocol and SQL dialect as on-prem MySQL</td>
</tr>
<tr class="even">
<td>No single point of failure</td>
<td><strong>Multi-AZ</strong> standby with automatic failover; endpoint does not change</td>
</tr>
<tr class="odd">
<td>Decoupled from the backend server</td>
<td>Database now lives on its own managed service, reachable only from the VPC</td>
</tr>
<tr class="even">
<td>Near-zero-downtime migration</td>
<td><strong>DMS</strong> replicates while the source stays live; a short cutover window at the end</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Same caveat as Chapter 12 applies here.</strong> DMS moves rows reliably, but by default only creates the objects needed to move data — <strong>secondary indexes, triggers, stored procedures and views need a separate schema export</strong> (e.g.&nbsp;<code>mysqldump</code> for schema only, then DMS for bulk load and change data capture). Confirm binary logging is enabled on the source for CDC before starting the task.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> For a database tier with “keep the app code as-is” as a hard requirement, an <strong>engine-compatible managed service plus a replication-based migration tool</strong> is the standard answer — it is exactly what makes this a <em>lift</em>-and-shift rather than a rewrite.</p>
</blockquote>
<hr>
</section>
<section id="sec-ingest" class="level2">
<h2 class="anchored" data-anchor-id="sec-ingest">14.6 Ingest the analytics data into AWS</h2>
<blockquote class="blockquote">
<ul>
<li>❓ The Hadoop workload’s dataset is “massive” and on-premises. How does it get into AWS, and does it need to move all at once?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    Q["Massive on-prem dataset&lt;br&gt;on HDFS"] --&gt; Q1{"Network bandwidth&lt;br&gt;enough for a timely transfer?"}
    Q1 --&gt;|"No — too big / too slow"| SNOW["AWS Snowball Edge - CHOSEN&lt;br&gt;for the one-time bulk seed"]
    Q1 --&gt;|"Yes, ongoing feed"| DS["AWS DataSync - CHOSEN&lt;br&gt;for ongoing incremental sync"]
    SNOW --&gt; S3["Amazon S3&lt;br&gt;raw zone"]
    DS --&gt; S3
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: a two-phase ingestion.</strong> A <strong>one-time bulk transfer</strong> with <strong>AWS Snowball Edge</strong> seeds the initial “massive” dataset without saturating a link that has not been sized for it, followed by <strong>AWS DataSync</strong> for the ongoing, incremental feed of new files landing on-premises after the seed.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Fit here</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AWS Snowball Edge</strong> (chosen, initial seed)</td>
<td>Physical device shipped to the data centre; avoids transferring the entire historical dataset over the network in one go</td>
</tr>
<tr class="even">
<td><strong>AWS DataSync</strong> (chosen, ongoing)</td>
<td>Automated, scheduled, checksum-verified sync of new/changed files from an on-prem NFS/HDFS-adjacent share to S3</td>
</tr>
<tr class="odd">
<td>A one-off <code>distcp</code> / manual copy</td>
<td>Rejected — no verification, no scheduling, no resumability at this data volume</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Why S3, not on-cluster HDFS, as the landing zone.</strong> The single biggest architectural decision in this chapter’s analytics track is <strong>landing data in Amazon S3 rather than on HDFS attached to the EMR cluster</strong>. It decouples storage from compute — the exact same benefit Chapter 11 found for the clickstream lake — and it is also what makes an EMR cluster <strong>safe to terminate</strong> between jobs (see <a href="#sec-emr">14.7</a>).</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Bulk-seed a large historical dataset with <strong>Snowball</strong>, then keep it current with <strong>DataSync</strong>. Either way, the destination is <strong>S3</strong>, because that is what lets the EMR layer above it be transient instead of permanent.</p>
</blockquote>
<hr>
</section>
<section id="sec-emr" class="level2">
<h2 class="anchored" data-anchor-id="sec-emr">14.7 Process the workload with Amazon EMR</h2>
<blockquote class="blockquote">
<ul>
<li>❓ The customer requires an EMR cluster. How do you run it in a way that’s actually cost-efficient and resilient, not just “technically EMR”?</li>
</ul>
</blockquote>
<section id="emr-cluster-shape-transient-not-persistent" class="level3">
<h3 class="anchored" data-anchor-id="emr-cluster-shape-transient-not-persistent">14.7.1 EMR cluster shape: transient, not persistent</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    W["Run existing Hadoop/Spark&lt;br&gt;jobs on EMR"] --&gt; Q1{"Does the cluster need&lt;br&gt;to run 24/7?"}
    Q1 --&gt;|"No — scheduled batch jobs"| TR["Transient cluster - CHOSEN&lt;br&gt;spin up, run, terminate"]
    Q1 --&gt;|"Yes — continuous processing"| PE["Persistent (long-running)&lt;br&gt;cluster"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Chosen: a transient EMR cluster</strong>, launched to run each batch job (or a scheduled job window) and <strong>terminated afterwards</strong>. Because the data lives in <strong>S3, not on-cluster HDFS</strong> (<a href="#sec-ingest">14.6</a>), terminating the cluster loses <strong>no data</strong> — the cluster is compute, not storage.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Transient cluster (chosen)</th>
<th>Persistent cluster</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pay for compute</td>
<td>Only while a job runs</td>
<td>24/7, whether processing or idle</td>
</tr>
<tr class="even">
<td>Data survives termination</td>
<td>Yes — it lives in S3 (EMRFS)</td>
<td>Only if data is also kept off-cluster</td>
</tr>
<tr class="odd">
<td>Fit here</td>
<td>Scheduled/batch Hadoop analytics</td>
<td>Continuous, always-on processing needs</td>
</tr>
</tbody>
</table>
</section>
<section id="emr-node-types-and-how-they-read-s3" class="level3">
<h3 class="anchored" data-anchor-id="emr-node-types-and-how-they-read-s3">14.7.2 EMR node types and how they read S3</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    S3R["S3 raw zone"] --&gt;|"EMRFS"| MST["Master node&lt;br&gt;cluster + job coordination"]
    MST --&gt; CORE["Core nodes&lt;br&gt;HDFS cache + compute"]
    MST --&gt; TASK["Task nodes&lt;br&gt;compute only, Spot-friendly"]
    CORE --&gt; S3C["S3 curated zone&lt;br&gt;job output"]
    TASK --&gt; S3C
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>EMRFS</strong> lets Hadoop/Spark address <code>s3://</code> paths as if they were HDFS, so the <strong>existing job code runs unmodified</strong> against S3.</li>
<li><strong>Master node</strong> coordinates the cluster; <strong>core nodes</strong> hold a local HDFS cache and run tasks; <strong>task nodes</strong> run compute only and hold no HDFS data — which is exactly why task nodes are the safe place to use <strong>Spot Instances</strong> (see <a href="#sec-resilient">14.12</a>).</li>
</ul>
</section>
<section id="why-not-emr-serverless-or-emr-on-eks-here" class="level3">
<h3 class="anchored" data-anchor-id="why-not-emr-serverless-or-emr-on-eks-here">14.7.3 Why not EMR Serverless or EMR on EKS here</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart TD
    Q["Compute layer for&lt;br&gt;the Hadoop workload"] --&gt; Q1{"Requirement says&lt;br&gt;'spin up an EMR cluster'?"}
    Q1 --&gt;|Yes| EMRC["EMR on EC2 - CHOSEN&lt;br&gt;satisfies the explicit ask"]
    Q1 --&gt;|"No constraint"| SRV["EMR Serverless&lt;br&gt;no cluster to manage"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Rejected option</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>EMR Serverless</strong></td>
<td>Removes cluster management entirely — a good default in general, but the brief explicitly asks for <strong>a cluster</strong>, and the team’s existing operational runbooks assume one</td>
</tr>
<tr class="even">
<td><strong>EMR on EKS</strong></td>
<td>Adds a Kubernetes control plane the team has no existing investment in; this workload has no Kubernetes requirement, unlike the Chapter 12 hybrid scenario</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> EMR’s job here is to run <strong>existing Hadoop/Spark code unchanged</strong> against data that lives in <strong>S3</strong>. Making the cluster <strong>transient</strong> and reading via <strong>EMRFS</strong> is what turns “we were told to use EMR” into a design that is also cost-efficient and resilient — not just compliant with the requirement.</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-query" class="level2">
<h2 class="anchored" data-anchor-id="sec-query">14.8 Catalog and query the lake</h2>
<blockquote class="blockquote">
<ul>
<li>❓ Once EMR has written curated output to S3, how does anyone run SQL against it without standing up a database?</li>
</ul>
</blockquote>
<p><strong>Chosen: AWS Glue Data Catalog for schema, Amazon Athena for ad hoc SQL</strong> — the same pattern as <a href="./11-serverless-data-analytics.html#sec-query">11.5</a>, reused here on EMR’s output instead of a clickstream.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    S3C["S3 curated zone&lt;br&gt;EMR job output"] --&gt; GDC["Glue Data Catalog&lt;br&gt;schema + partitions"]
    GDC --&gt; ATH["Amazon Athena&lt;br&gt;serverless SQL"]
    S3C --&gt; ATH
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>How it’s met</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SQL access to EMR’s output, no extra servers</td>
<td>Athena queries the curated S3 zone directly; no database to provision</td>
</tr>
<tr class="even">
<td>Schema shared between EMR and Athena</td>
<td>A <strong>Glue crawler</strong> (or an EMR step that registers partitions) keeps the Data Catalog in sync with what EMR writes</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> EMR does the heavy processing; <strong>Glue + Athena</strong> is the lightweight, serverless way to make the <em>result</em> queryable without adding a second always-on cluster.</p>
</blockquote>
<hr>
</section>
<section id="sec-visualise" class="level2">
<h2 class="anchored" data-anchor-id="sec-visualise">14.9 Visualise the insight</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How do the business users who currently use the on-prem visualisation tools see the same insights on AWS?</li>
</ul>
</blockquote>
<p><strong>Chosen: Amazon QuickSight</strong>, reading through Athena — the same choice as <a href="./11-serverless-data-analytics.html#sec-visualise">11.6</a>.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    ATH["Amazon Athena"] --&gt; QS["Amazon QuickSight&lt;br&gt;dashboards + SPICE"]
    QS --&gt; U["Business users&lt;br&gt;replace on-prem viz tools"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>QuickSight strength</th>
<th>Why it fits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Serverless, pay-per-session readers</td>
<td>No new licensing model to negotiate for existing report consumers</td>
</tr>
<tr class="even">
<td>SPICE in-memory cache</td>
<td>Dashboards stay fast without re-querying Athena on every click</td>
</tr>
<tr class="odd">
<td>Sits directly on Athena</td>
<td>No extra data movement beyond what EMR already wrote to S3</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Visualisation is the one place where “it’s up to you” genuinely means <em>pick the simplest thing that replaces what the customer already has</em> — QuickSight-on-Athena does that without inventing a new data path.</p>
</blockquote>
<hr>
</section>
<section id="sec-secure" class="level2">
<h2 class="anchored" data-anchor-id="sec-secure">14.10 Secure both tracks</h2>
<blockquote class="blockquote">
<ul>
<li>❓ Two workloads, one VPC — what security posture has to hold for both at once?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    subgraph Transit["In transit"]
        T1["HTTPS via&lt;br&gt;CloudFront + ALB"]
        T2["TLS: DMS, DataSync,&lt;br&gt;EMRFS to S3"]
    end
    subgraph Rest["At rest"]
        R1["SSE-KMS on&lt;br&gt;every S3 bucket"]
        R2["RDS storage&lt;br&gt;encryption"]
    end
    subgraph Identity["Identity"]
        I1["ECS task role:&lt;br&gt;only its own resources"]
        I2["EMR service +&lt;br&gt;instance roles, scoped to S3"]
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>Control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Public app tier protected</td>
<td><strong>AWS WAF</strong> on CloudFront and the ALB</td>
</tr>
<tr class="even">
<td>App tiers isolated from each other</td>
<td>Security groups per tier: ALB → ECS tasks → RDS, no direct internet-to-database path</td>
</tr>
<tr class="odd">
<td>Analytics data protected in transit and at rest</td>
<td>TLS on DataSync/DMS/EMRFS transfers; <strong>SSE-KMS</strong> on every S3 bucket (raw, curated)</td>
</tr>
<tr class="even">
<td>Least privilege per workload</td>
<td>Separate IAM roles for the ECS task, the DMS replication instance, and the EMR cluster’s service and instance profiles — each scoped only to the resources it needs</td>
</tr>
<tr class="odd">
<td>Database reachable only from the backend</td>
<td>RDS in a private subnet, security group allowing inbound only from the ECS tasks’ security group</td>
</tr>
</tbody>
</table>
<p>For IAM roles, KMS and the shared responsibility model, see <a href="./02-security.html">02. Security</a>.</p>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Running two workloads in one account does not mean one security posture. <strong>Scope every role — ECS task, DMS instance, EMR cluster — to only the S3 prefixes and databases it touches.</strong></p>
</blockquote>
<hr>
</section>
<section id="sec-observability" class="level2">
<h2 class="anchored" data-anchor-id="sec-observability">14.11 Make both tracks observable</h2>
<blockquote class="blockquote">
<ul>
<li>❓ A backend outage is loud. A stalled analytics pipeline is silent. How do you catch both?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    ALB["ALB + ECS"] --&gt; CW["Amazon CloudWatch&lt;br&gt;metrics, logs, alarms"]
    RDS["RDS for MySQL"] --&gt; CW
    DS["DataSync tasks"] --&gt; CW
    EMR["EMR cluster + steps"] --&gt; CW
    ATH["Athena"] --&gt; CW
    CW --&gt; AL["Alarms to SNS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Track</th>
<th>Signal worth alarming on</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>App tier</td>
<td>ALB <code>5XXCount</code>, ECS service task health, RDS <code>FreeStorageSpace</code> / <code>CPUUtilization</code> / replication lag</td>
</tr>
<tr class="even">
<td>Analytics tier</td>
<td>DataSync task success/failure, <strong>EMR step failures</strong>, EMR cluster idle time (a cost signal, not just health), Athena <code>ProcessedBytes</code></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Alarm on the app tier’s <strong>errors</strong> and the analytics tier’s <strong>absence of progress</strong> (a step that never completes, a DataSync task that stops running) — the same “pipelines fail silently” lesson from <a href="./11-serverless-data-analytics.html#sec-observability">11.8</a> applies directly to EMR steps.</p>
</blockquote>
<hr>
</section>
<section id="sec-resilient" class="level2">
<h2 class="anchored" data-anchor-id="sec-resilient">14.12 Cut over safely, and control cost</h2>
<blockquote class="blockquote">
<ul>
<li>❓ How do you switch traffic to AWS without a big-bang outage, and keep the EMR side affordable?</li>
</ul>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    A["DMS replicates&lt;br&gt;MySQL, source stays live"] --&gt; B["DataSync keeps S3&lt;br&gt;current with on-prem"]
    B --&gt; C["Test app + EMR jobs&lt;br&gt;against AWS copies"]
    C --&gt; D["Cutover: point DNS,&lt;br&gt;stop on-prem writes"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li><strong>Database cutover:</strong> keep DMS replicating (CDC) until the switch, then a short, planned cutover window — the same near-zero-downtime pattern as <a href="./12-hybrid-container-workloads.html#sec-db">12.5.5</a>.</li>
<li><strong>Analytics cutover:</strong> run the EMR pipeline against synced S3 data in parallel with the on-prem Hadoop cluster until outputs are verified to match, before decommissioning the physical cluster.</li>
<li><strong>Cost levers for EMR:</strong> use <strong>Spot Instances on task nodes only</strong> (they hold no HDFS data, so interruption just delays a job, it doesn’t lose it); terminate the cluster between scheduled runs; keep S3 storage on <strong>Intelligent-Tiering</strong> for the raw zone.</li>
<li><strong>Cost levers for the app tier:</strong> ECS Service Auto Scaling to match ALB traffic; RDS storage auto scaling instead of over-provisioning up front.</li>
</ul>
<p>For broader cost and resilience patterns, see <a href="./08-optimization.html">08. Optimization</a>.</p>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> Both cutovers follow the same shape — <strong>replicate in parallel, verify, then switch</strong> — and both cost profiles improve the same way: <strong>pay for compute only while it’s doing something</strong> (ECS auto scaling, transient EMR, Spot task nodes).</p>
</blockquote>
<hr>
</section>
<section id="sec-reference" class="level2">
<h2 class="anchored" data-anchor-id="sec-reference">14.13 The reference architecture, end to end</h2>
<p>Two focused diagrams — one per workload — are easier to review (and to draw correctly) than a single diagram trying to hold both at once.</p>
<p><strong>Application tier on AWS</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    USERS["Internet users"] --&gt; CF["CloudFront + WAF"]
    CF --&gt;|"static"| S3F["S3&lt;br&gt;frontend"]
    CF --&gt;|"dynamic"| ALB["Application&lt;br&gt;Load Balancer"]
    ALB --&gt; ECS["ECS on Fargate&lt;br&gt;Java backend"]
    ECS --&gt; RDS["RDS for MySQL&lt;br&gt;Multi-AZ"]
    DMS["AWS DMS"] --&gt;|"migrate"| RDS
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Analytics tier on AWS</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    ONPREM["On-prem HDFS&lt;br&gt;dataset"] --&gt;|"bulk seed"| SNOW["Snowball Edge"]
    ONPREM --&gt;|"ongoing"| DS["AWS DataSync"]
    SNOW --&gt; S3R["S3 raw zone"]
    DS --&gt; S3R
    S3R --&gt;|"EMRFS"| EMR["Amazon EMR&lt;br&gt;transient cluster"]
    EMR --&gt; S3C["S3 curated zone"]
    S3C --&gt; GDC["Glue Data Catalog"]
    GDC --&gt; ATH["Amazon Athena"]
    S3C --&gt; ATH
    ATH --&gt; QS["Amazon QuickSight"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>How each requirement is satisfied</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Requirement</th>
<th>Where it is met</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decouple frontend, backend, database</td>
<td>S3+CloudFront / ECS on Fargate+ALB / RDS for MySQL — three independent services, no shared server</td>
</tr>
<tr class="even">
<td>No app rewrite</td>
<td>Backend is containerised, not rewritten; database engine is unchanged</td>
</tr>
<tr class="odd">
<td>Host both workloads in the cloud</td>
<td>Application tier and analytics tier both run entirely on AWS, in one VPC</td>
</tr>
<tr class="even">
<td>Analytics must run on Amazon EMR</td>
<td>Transient EMR cluster, reading/writing S3 via EMRFS</td>
</tr>
<tr class="odd">
<td>Architect’s choice of ingest/store/visualise</td>
<td>Snowball + DataSync ingest; S3 store; Glue + Athena query; QuickSight visualise</td>
</tr>
<tr class="even">
<td>No single point of failure</td>
<td>Multi-AZ RDS, multi-AZ ECS tasks, CloudFront edge distribution, EMR data safe in S3 independent of cluster life</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="sec-not" class="level2">
<h2 class="anchored" data-anchor-id="sec-not">14.14 When <em>not</em> to build it this way</h2>
<p>An honest architect states the boundaries of their own recommendation.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symptom</th>
<th>Why this design struggles</th>
<th>Better fit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Analytics needs sub-second, always-on processing</td>
<td>Transient EMR is batch-shaped</td>
<td>A persistent EMR cluster, or a streaming service as in <a href="./11-serverless-data-analytics.html">11. Serverless Data Analytics</a></td>
</tr>
<tr class="even">
<td>No constraint to use a cluster at all</td>
<td>EMR (on EC2) still carries cluster concepts to manage</td>
<td><strong>EMR Serverless</strong>, once the “spin up a cluster” requirement is gone</td>
</tr>
<tr class="odd">
<td>Backend needs a custom AMI or host-level SSH</td>
<td>Fargate gives no host access</td>
<td><strong>ECS on EC2</strong>, as in <a href="./12-hybrid-container-workloads.html#sec-compute">12.4</a></td>
</tr>
<tr class="even">
<td>Team already has deep Kubernetes investment</td>
<td>ECS/EMR-on-EC2 underuses that skill</td>
<td><strong>EKS</strong> for the app tier, <strong>EMR on EKS</strong> for analytics</td>
</tr>
<tr class="odd">
<td>Heavy, predictable, always-on BI workload at scale</td>
<td>Athena’s per-scan pricing stops being the cheapest option</td>
<td><strong>Amazon Redshift</strong></td>
</tr>
<tr class="even">
<td>Database needs read scaling beyond one primary</td>
<td>A single RDS instance</td>
<td>Add <strong>RDS read replicas</strong>, as in <a href="./12-hybrid-container-workloads.html#sec-db">12.5.3</a></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Architect’s takeaway:</strong> This design is optimal for <strong>batch-shaped Hadoop analytics with a mandated EMR cluster, alongside a public three-tier app that needs decoupling but not a rewrite</strong>. Change the traffic pattern, the team’s skills, or the “must use EMR” constraint, and the winning services change with it.</p>
</blockquote>
<hr>
</section>
<section id="sec-cheatsheet" class="level2">
<h2 class="anchored" data-anchor-id="sec-cheatsheet">14.15 Architect’s cheat sheet</h2>
<p>The cloud decision-making for the requirement mentioned in the beginning of the blog:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#E3F2FD', 'primaryBorderColor': '#1E88E5', 'lineColor': '#424242', 'fontSize': '14px'}}}%%
flowchart LR
    ROOT["Capstone:&lt;br&gt;app + EMR analytics"]

    ROOT --&gt; APP["App tier"]
    APP --&gt; A1["Frontend to S3&lt;br&gt;+ CloudFront"]
    APP --&gt; A2["Backend containerised&lt;br&gt;on ECS Fargate"]
    APP --&gt; A3["Database lift-and-shift&lt;br&gt;to RDS + DMS"]

    ROOT --&gt; AN["Analytics tier"]
    AN --&gt; N1["Snowball for bulk seed,&lt;br&gt;DataSync ongoing"]
    AN --&gt; N2["S3 = the landing zone,&lt;br&gt;not on-cluster HDFS"]
    AN --&gt; N3["EMR = transient,&lt;br&gt;reads via EMRFS"]
    AN --&gt; N4["Glue + Athena +&lt;br&gt;QuickSight on top"]

    ROOT --&gt; X["Cross-cutting"]
    X --&gt; X1["Scope every IAM role&lt;br&gt;to its own resources"]
    X --&gt; X2["Encrypt in transit&lt;br&gt;and at rest"]
    X --&gt; X3["Alarm on errors AND&lt;br&gt;on silent pipeline stalls"]
    X --&gt; X4["Replicate in parallel,&lt;br&gt;verify, then cut over"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ol type="1">
<li>Two workloads sharing one data centre and one power feed is a <strong>single blast radius</strong> — decoupling removes that shared failure domain.</li>
<li><strong>Refactor where it’s cheap</strong> (static frontend → S3), <strong>refactor lightly where it buys resilience</strong> (containerise the backend, don’t rewrite it), <strong>lift-and-shift where compatibility matters most</strong> (MySQL → RDS for MySQL).</li>
<li><strong>Frontend → S3 + CloudFront</strong>: no server-side logic to preserve, so there is nothing to “rewrite” — only to relocate.</li>
<li><strong>Backend → ECS on Fargate + ALB</strong>: containerising is a packaging change, not a code change.</li>
<li><strong>Database → RDS for MySQL + DMS</strong>: same wire protocol and SQL dialect keeps the application’s data-access code untouched.</li>
<li><strong>DMS moves data, not the whole schema</strong> — export secondary indexes, triggers and stored procedures separately.</li>
<li>A <strong>mandated EMR cluster</strong> is a fixed point that shapes every ingestion and storage decision around it — check it does not get silently bypassed.</li>
<li><strong>Land analytics data in S3, not on-cluster HDFS</strong> — this single choice is what makes the EMR cluster safe to terminate.</li>
<li><strong>Transient EMR clusters</strong> cost less than persistent ones when jobs are scheduled/batch, precisely because the data survives termination in S3.</li>
<li><strong>EMRFS</strong> lets existing Hadoop/Spark code address <code>s3://</code> paths unmodified — no job rewrite needed.</li>
<li><strong>Core nodes</strong> cache HDFS data; <strong>task nodes</strong> are compute-only — task nodes are the safe place for <strong>Spot Instances</strong>.</li>
<li>Reject <strong>EMR Serverless</strong> only when the requirement explicitly asks for a managed <strong>cluster</strong>; otherwise it is usually the simpler default.</li>
<li><strong>Snowball Edge</strong> for the one-time bulk historical seed; <strong>DataSync</strong> for the ongoing incremental feed — pick based on data volume vs.&nbsp;link bandwidth.</li>
<li><strong>Glue Data Catalog + Athena</strong> turn EMR’s S3 output into ad hoc SQL without a second always-on database.</li>
<li><strong>QuickSight on Athena</strong> replaces on-prem visualisation tools without inventing a new data path.</li>
<li>Scope <strong>every IAM role separately</strong> — ECS task, DMS replication instance, EMR service/instance profile — to only what it needs.</li>
<li><strong>Encrypt in transit and at rest</strong> on both tracks: TLS everywhere, SSE-KMS on every bucket, RDS storage encryption.</li>
<li>App-tier failures are <strong>loud</strong> (5XX errors); analytics-tier failures are <strong>silent</strong> (a stalled EMR step, a paused DataSync task) — alarm on both kinds.</li>
<li>Cut over both tracks the same way: <strong>replicate in parallel with the source live, verify outputs match, then switch</strong> — never a big-bang cutover.</li>
<li>Cost control on both tracks follows one rule: <strong>pay for compute only while it is doing something</strong> — ECS auto scaling, transient EMR, Spot task nodes.</li>
<li>Draw <strong>one diagram per workload</strong>, not one diagram for everything — it is easier to review, and easier to get right.</li>
<li>“Technically satisfies the requirement” (an EMR cluster) is not the same as “well-architected” — make the cluster transient and S3-backed, or you have complied with the letter of the ask while paying for the worst version of it.</li>
</ol>
<hr>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<p><em>Inspired from Capstone Project Question</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-multi-account-strategies.html" class="pagination-link" aria-label="13. Architecting for Account Governance and Multi-Account Management">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">13. Architecting for Account Governance and Multi-Account Management</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>