# 9. Additional References

- AWS Coursera Course on `AWS Technical Essentials`

- [My ChatGPT Interactions on Networking in AWS](https://chatgpt.com/share/67077451-51e0-800f-ad65-98c6b109e330)
- [My ChatGPT Interactions on Computing in AWS](https://chatgpt.com/share/6703b5e9-1154-800f-8c1d-03f16c3ae6e0)
- [My ChatGPT Interactions on Storage Services in AWS](https://chatgpt.com/share/6728503c-722c-800f-a6fc-f16d4e1888f3)
- [My ChatGPT Interactions on Database Services in AWS](https://chatgpt.com/share/67285596-cb00-800f-b999-f317d4ae56c4)

> Disclaimer: Beware: Not all information provided by ChatGPT is accurate. They get wrong quite a lot in nuanced sub-topics. 


---

# **Plagiarism Disclosure**: <br>
> - The above notes contain my own writing like mermaid charts and bullet points combined with my notes from Coursera course (not to be misjudged for plagiarism).
<br>
> - Most pics are from the Coursera course. If a pic is taken from outside, source is cited below it
<br>
> - I have plenty of interactions with ChatGPT weaved into appropriate sections for better reading
<br>
> - The above notes are purely to refresh my memory when I take up any AWS exam in future. 

